// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AdminCreateUserInput struct {
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	Role       *UserRole `json:"role,omitempty"`
	IsVerified *bool     `json:"isVerified,omitempty"`
}

type AuthPayload struct {
	Token        string    `json:"token"`
	RefreshToken string    `json:"refreshToken"`
	User         *User     `json:"user"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

type BatchUpdateCategoriesInput struct {
	PostIds    []string     `json:"postIds"`
	Categories []string     `json:"categories"`
	Operation  TagOperation `json:"operation"`
}

type BatchUpdateTagsInput struct {
	PostIds   []string     `json:"postIds"`
	Tags      []string     `json:"tags"`
	Operation TagOperation `json:"operation"`
}

type BlogPost struct {
	ID            string             `json:"id"`
	AuthorID      string             `json:"authorId"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Excerpt       *string            `json:"excerpt,omitempty"`
	Content       string             `json:"content"`
	Tags          []string           `json:"tags"`
	Categories    []string           `json:"categories"`
	CoverImageURL *string            `json:"coverImageUrl,omitempty"`
	AccessLevel   AccessLevel        `json:"accessLevel"`
	Status        PostStatus         `json:"status"`
	PublishedAt   *time.Time         `json:"publishedAt,omitempty"`
	LastEditedAt  *time.Time         `json:"lastEditedAt,omitempty"`
	CreatedAt     time.Time          `json:"createdAt"`
	UpdatedAt     time.Time          `json:"updatedAt"`
	NotionPageID  *string            `json:"notionPageId,omitempty"`
	Author        *User              `json:"author"`
	Versions      []*BlogPostVersion `json:"versions"`
	Stats         *BlogPostStats     `json:"stats"`
	IsLiked       bool               `json:"isLiked"`
}

type BlogPostComment struct {
	ID          string             `json:"id"`
	Content     string             `json:"content"`
	BlogPost    *BlogPost          `json:"blogPost"`
	User        *User              `json:"user"`
	Parent      *BlogPostComment   `json:"parent,omitempty"`
	Replies     []*BlogPostComment `json:"replies"`
	IsApproved  bool               `json:"isApproved"`
	LikeCount   int                `json:"likeCount"`
	ReportCount int                `json:"reportCount"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

type BlogPostStats struct {
	ID           string     `json:"id"`
	ViewCount    int        `json:"viewCount"`
	LikeCount    int        `json:"likeCount"`
	ShareCount   int        `json:"shareCount"`
	CommentCount int        `json:"commentCount"`
	LastViewedAt *time.Time `json:"lastViewedAt,omitempty"`
	UpdatedAt    time.Time  `json:"updatedAt"`
}

type BlogPostVersion struct {
	ID         string    `json:"id"`
	VersionNum int       `json:"versionNum"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	ChangeLog  *string   `json:"changeLog,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
	CreatedBy  *User     `json:"createdBy"`
}

type CategoryInfo struct {
	Name  string      `json:"name"`
	Count int         `json:"count"`
	Posts []*BlogPost `json:"posts"`
}

type CommentFilterInput struct {
	BlogPostID *string `json:"blogPostId,omitempty"`
	UserID     *string `json:"userId,omitempty"`
	IsApproved *bool   `json:"isApproved,omitempty"`
}

type CommentResult struct {
	Comments []*BlogPostComment `json:"comments"`
	Total    int                `json:"total"`
}

type CommentSortInput struct {
	Field *string `json:"field,omitempty"`
	Order *string `json:"order,omitempty"`
}

type ConfirmPasswordResetInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type CreateCommentInput struct {
	Content    string  `json:"content"`
	BlogPostID string  `json:"blogPostId"`
	ParentID   *string `json:"parentId,omitempty"`
}

type CreateInviteCodeInput struct {
	ExpiresAt   time.Time `json:"expiresAt"`
	MaxUses     *int      `json:"maxUses,omitempty"`
	Description *string   `json:"description,omitempty"`
}

type CreatePostInput struct {
	Title         string       `json:"title"`
	Slug          *string      `json:"slug,omitempty"`
	Excerpt       *string      `json:"excerpt,omitempty"`
	Content       string       `json:"content"`
	Tags          []string     `json:"tags,omitempty"`
	Categories    []string     `json:"categories,omitempty"`
	CoverImageURL *string      `json:"coverImageUrl,omitempty"`
	AccessLevel   *AccessLevel `json:"accessLevel,omitempty"`
	Status        *PostStatus  `json:"status,omitempty"`
	PublishAt     *time.Time   `json:"publishAt,omitempty"`
}

type EmailLoginInput struct {
	Email string `json:"email"`
}

type EnhancedSearchResult struct {
	Posts       []*BlogPost   `json:"posts"`
	Total       int           `json:"total"`
	Took        string        `json:"took"`
	Suggestions []string      `json:"suggestions"`
	Facets      *SearchFacets `json:"facets"`
}

type GeneralResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	Code    *string `json:"code,omitempty"`
}

type GitHubConfig struct {
	Repo  string `json:"repo"`
	Token string `json:"token"`
}

type ImageUploadResponse struct {
	ImageURL  string  `json:"imageUrl"`
	DeleteURL *string `json:"deleteUrl,omitempty"`
	Filename  string  `json:"filename"`
	Size      int     `json:"size"`
}

type InviteCode struct {
	ID          string     `json:"id"`
	Code        string     `json:"code"`
	CreatedBy   *User      `json:"createdBy"`
	UsedBy      *User      `json:"usedBy,omitempty"`
	UsedAt      *time.Time `json:"usedAt,omitempty"`
	ExpiresAt   time.Time  `json:"expiresAt"`
	MaxUses     int        `json:"maxUses"`
	CurrentUses int        `json:"currentUses"`
	IsActive    bool       `json:"isActive"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type LoginInput struct {
	Identifier string `json:"identifier"`
	Password   string `json:"password"`
	Remember   *bool  `json:"remember,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID             string           `json:"id"`
	Type           NotificationType `json:"type"`
	Title          string           `json:"title"`
	Content        string           `json:"content"`
	RelatedPost    *BlogPost        `json:"relatedPost,omitempty"`
	RelatedComment *BlogPostComment `json:"relatedComment,omitempty"`
	RelatedUser    *User            `json:"relatedUser,omitempty"`
	Recipient      *User            `json:"recipient"`
	IsRead         bool             `json:"isRead"`
	CreatedAt      time.Time        `json:"createdAt"`
}

type NotionPage struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	LastEditedAt time.Time `json:"lastEditedAt"`
	URL          string    `json:"url"`
}

type PopularQuery struct {
	Query        string    `json:"query"`
	Count        int       `json:"count"`
	LastSearched time.Time `json:"lastSearched"`
}

type PostFilterInput struct {
	AuthorID    *string      `json:"authorId,omitempty"`
	Status      *PostStatus  `json:"status,omitempty"`
	AccessLevel *AccessLevel `json:"accessLevel,omitempty"`
	Tags        []string     `json:"tags,omitempty"`
	Categories  []string     `json:"categories,omitempty"`
	Search      *string      `json:"search,omitempty"`
	DateFrom    *time.Time   `json:"dateFrom,omitempty"`
	DateTo      *time.Time   `json:"dateTo,omitempty"`
}

type PostSortInput struct {
	Field *string `json:"field,omitempty"`
	Order *string `json:"order,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Username   string  `json:"username"`
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	InviteCode *string `json:"inviteCode,omitempty"`
}

type RequestPasswordResetInput struct {
	Email string `json:"email"`
}

type SearchFacetItem struct {
	Value string `json:"value"`
	Count int    `json:"count"`
}

type SearchFacets struct {
	Tags       []*SearchFacetItem `json:"tags"`
	Categories []*SearchFacetItem `json:"categories"`
	Authors    []*SearchFacetItem `json:"authors"`
}

type SearchFilters struct {
	AuthorID   *string    `json:"authorId,omitempty"`
	Tags       []string   `json:"tags,omitempty"`
	Categories []string   `json:"categories,omitempty"`
	DateFrom   *time.Time `json:"dateFrom,omitempty"`
	DateTo     *time.Time `json:"dateTo,omitempty"`
	MinViews   *int       `json:"minViews,omitempty"`
	MinLikes   *int       `json:"minLikes,omitempty"`
}

type SearchInput struct {
	Query   string         `json:"query"`
	Limit   *int           `json:"limit,omitempty"`
	Offset  *int           `json:"offset,omitempty"`
	Filters *SearchFilters `json:"filters,omitempty"`
	SortBy  *string        `json:"sortBy,omitempty"`
}

type SearchResult struct {
	Posts []*BlogPost `json:"posts"`
	Total int         `json:"total"`
	Took  string      `json:"took"`
}

type SearchStats struct {
	TotalSearches  int             `json:"totalSearches"`
	PopularQueries []*PopularQuery `json:"popularQueries"`
	SearchTrends   []*SearchTrend  `json:"searchTrends"`
}

type SearchTrend struct {
	Date        string   `json:"date"`
	SearchCount int      `json:"searchCount"`
	TopQueries  []string `json:"topQueries"`
}

type ServerDashboard struct {
	ServerTime         time.Time          `json:"serverTime"`
	Hostname           string             `json:"hostname"`
	GoVersion          string             `json:"goVersion"`
	CPUCount           int                `json:"cpuCount"`
	Goroutines         int                `json:"goroutines"`
	Memory             *ServerMemoryStats `json:"memory"`
	Uptime             string             `json:"uptime"`
	UserCount          int                `json:"userCount"`
	PostCount          int                `json:"postCount"`
	TodayRegistrations int                `json:"todayRegistrations"`
	TodayPosts         int                `json:"todayPosts"`
}

type ServerMemoryStats struct {
	Alloc      string `json:"alloc"`
	TotalAlloc string `json:"totalAlloc"`
	Sys        string `json:"sys"`
	HeapAlloc  string `json:"heapAlloc"`
	HeapSys    string `json:"heapSys"`
}

type TagCategoryStats struct {
	TotalTags       int             `json:"totalTags"`
	TotalCategories int             `json:"totalCategories"`
	Tags            []*TagInfo      `json:"tags"`
	Categories      []*CategoryInfo `json:"categories"`
}

type TagInfo struct {
	Name  string      `json:"name"`
	Count int         `json:"count"`
	Posts []*BlogPost `json:"posts"`
}

type UpdateCommentInput struct {
	Content string `json:"content"`
}

type UpdatePostInput struct {
	Title         *string      `json:"title,omitempty"`
	Slug          *string      `json:"slug,omitempty"`
	Excerpt       *string      `json:"excerpt,omitempty"`
	Content       *string      `json:"content,omitempty"`
	Tags          []string     `json:"tags,omitempty"`
	Categories    []string     `json:"categories,omitempty"`
	CoverImageURL *string      `json:"coverImageUrl,omitempty"`
	AccessLevel   *AccessLevel `json:"accessLevel,omitempty"`
	Status        *PostStatus  `json:"status,omitempty"`
	ChangeLog     *string      `json:"changeLog,omitempty"`
}

type UpdateProfileInput struct {
	Username *string `json:"username,omitempty"`
	Bio      *string `json:"bio,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
}

type User struct {
	ID              string      `json:"id"`
	Username        string      `json:"username"`
	Email           string      `json:"email"`
	Role            UserRole    `json:"role"`
	IsVerified      bool        `json:"isVerified"`
	IsActive        bool        `json:"isActive"`
	Avatar          *string     `json:"avatar,omitempty"`
	Bio             *string     `json:"bio,omitempty"`
	LastLoginAt     *time.Time  `json:"lastLoginAt,omitempty"`
	EmailVerifiedAt *time.Time  `json:"emailVerifiedAt,omitempty"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
	Posts           []*BlogPost `json:"posts"`
	PostsCount      int         `json:"postsCount"`
}

type VerifyEmailInput struct {
	Email string           `json:"email"`
	Code  string           `json:"code"`
	Type  VerificationType `json:"type"`
}

type AccessLevel string

const (
	AccessLevelPublic     AccessLevel = "PUBLIC"
	AccessLevelPrivate    AccessLevel = "PRIVATE"
	AccessLevelRestricted AccessLevel = "RESTRICTED"
)

var AllAccessLevel = []AccessLevel{
	AccessLevelPublic,
	AccessLevelPrivate,
	AccessLevelRestricted,
}

func (e AccessLevel) IsValid() bool {
	switch e {
	case AccessLevelPublic, AccessLevelPrivate, AccessLevelRestricted:
		return true
	}
	return false
}

func (e AccessLevel) String() string {
	return string(e)
}

func (e *AccessLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessLevel", str)
	}
	return nil
}

func (e AccessLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotificationType string

const (
	NotificationTypeCommentReply NotificationType = "COMMENT_REPLY"
	NotificationTypePostLike     NotificationType = "POST_LIKE"
	NotificationTypePostComment  NotificationType = "POST_COMMENT"
	NotificationTypeSystem       NotificationType = "SYSTEM"
)

var AllNotificationType = []NotificationType{
	NotificationTypeCommentReply,
	NotificationTypePostLike,
	NotificationTypePostComment,
	NotificationTypeSystem,
}

func (e NotificationType) IsValid() bool {
	switch e {
	case NotificationTypeCommentReply, NotificationTypePostLike, NotificationTypePostComment, NotificationTypeSystem:
		return true
	}
	return false
}

func (e NotificationType) String() string {
	return string(e)
}

func (e *NotificationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationType", str)
	}
	return nil
}

func (e NotificationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PostStatus string

const (
	PostStatusDraft     PostStatus = "DRAFT"
	PostStatusPublished PostStatus = "PUBLISHED"
	PostStatusArchived  PostStatus = "ARCHIVED"
)

var AllPostStatus = []PostStatus{
	PostStatusDraft,
	PostStatusPublished,
	PostStatusArchived,
}

func (e PostStatus) IsValid() bool {
	switch e {
	case PostStatusDraft, PostStatusPublished, PostStatusArchived:
		return true
	}
	return false
}

func (e PostStatus) String() string {
	return string(e)
}

func (e *PostStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostStatus", str)
	}
	return nil
}

func (e PostStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PostStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PostStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TagOperation string

const (
	TagOperationAdd     TagOperation = "ADD"
	TagOperationReplace TagOperation = "REPLACE"
)

var AllTagOperation = []TagOperation{
	TagOperationAdd,
	TagOperationReplace,
}

func (e TagOperation) IsValid() bool {
	switch e {
	case TagOperationAdd, TagOperationReplace:
		return true
	}
	return false
}

func (e TagOperation) String() string {
	return string(e)
}

func (e *TagOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TagOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TagOperation", str)
	}
	return nil
}

func (e TagOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TagOperation) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TagOperation) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "USER"
	UserRoleAdmin UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleUser,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleUser, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VerificationType string

const (
	VerificationTypeRegister      VerificationType = "REGISTER"
	VerificationTypeLogin         VerificationType = "LOGIN"
	VerificationTypeResetPassword VerificationType = "RESET_PASSWORD"
)

var AllVerificationType = []VerificationType{
	VerificationTypeRegister,
	VerificationTypeLogin,
	VerificationTypeResetPassword,
}

func (e VerificationType) IsValid() bool {
	switch e {
	case VerificationTypeRegister, VerificationTypeLogin, VerificationTypeResetPassword:
		return true
	}
	return false
}

func (e VerificationType) String() string {
	return string(e)
}

func (e *VerificationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VerificationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VerificationType", str)
	}
	return nil
}

func (e VerificationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VerificationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VerificationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
