package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"os"
	"repair-platform/middleware"
	"repair-platform/models"
	"repair-platform/services"
	"runtime"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*AuthPayload, error) {
	logger := middleware.GetLogger()
	authService := services.NewAuthService(r.DB)

	// 转换输入
	registerInput := &models.RegisterInput{
		Username:   input.Username,
		Email:      input.Email,
		Password:   input.Password,
		InviteCode: "",
	}

	if input.InviteCode != nil {
		registerInput.InviteCode = *input.InviteCode
	}

	logger.Infow("开始用户注册", "username", input.Username, "email", input.Email)

	// 调用认证服务
	user, token, err := authService.Register(registerInput)
	if err != nil {
		logger.Errorw("用户注册失败", "error", err, "username", input.Username)
		return nil, err
	}

	logger.Infow("用户注册成功", "userID", user.ID, "username", user.Username)

	// 生成刷新token
	refreshToken, err := models.GenerateJWT(user.ID, user.Username, user.Role, true)
	if err != nil {
		logger.Errorw("生成刷新token失败", "error", err)
		refreshToken = "" // 如果失败就不返回刷新token
	}

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    time.Now().Add(24 * time.Hour),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	logger := middleware.GetLogger()
	authService := services.NewAuthService(r.DB)

	// 转换输入
	loginInput := &models.LoginInput{
		Identifier: input.Identifier,
		Password:   input.Password,
	}

	logger.Infow("开始用户登录", "identifier", input.Identifier)

	// 调用认证服务
	user, token, err := authService.Login(loginInput)
	if err != nil {
		logger.Errorw("用户登录失败", "error", err, "identifier", input.Identifier)
		return nil, err
	}

	logger.Infow("用户登录成功", "userID", user.ID, "username", user.Username)

	// 生成刷新token
	refreshToken, err := models.GenerateJWT(user.ID, user.Username, user.Role, true)
	if err != nil {
		logger.Errorw("生成刷新token失败", "error", err)
		refreshToken = "" // 如果失败就不返回刷新token
	}

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    time.Now().Add(24 * time.Hour),
	}, nil
}

// EmailLogin is the resolver for the emailLogin field.
func (r *mutationResolver) EmailLogin(ctx context.Context, input EmailLoginInput) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	authService := services.NewAuthService(r.DB)

	logger.Infow("开始邮箱登录", "email", input.Email)

	// 发送验证码
	err := authService.SendEmailLoginCode(input.Email)
	if err != nil {
		logger.Errorw("发送邮箱登录验证码失败", "error", err, "email", input.Email)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("发送验证码失败"),
			Code:    strPtr("SEND_CODE_FAILED"),
		}, nil
	}

	logger.Infow("邮箱登录验证码发送成功", "email", input.Email)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("验证码已发送到您的邮箱"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// VerifyEmailAndLogin is the resolver for the verifyEmailAndLogin field.
func (r *mutationResolver) VerifyEmailAndLogin(ctx context.Context, input VerifyEmailInput) (*AuthPayload, error) {
	logger := middleware.GetLogger()
	authService := services.NewAuthService(r.DB)

	// 转换输入
	verifyInput := &models.VerifyEmailInput{
		Email: input.Email,
		Code:  input.Code,
		Type:  string(input.Type),
	}

	logger.Infow("开始验证邮箱并登录", "email", input.Email, "type", input.Type)

	// 调用认证服务
	user, token, refreshToken, err := authService.VerifyEmailAndLogin(verifyInput)
	if err != nil {
		logger.Errorw("验证邮箱并登录失败", "error", err, "email", input.Email)
		return nil, err
	}

	logger.Infow("验证邮箱并登录成功", "userID", user.ID, "username", user.Username)

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    time.Now().Add(24 * time.Hour),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*GeneralResponse, error) {
	logger := middleware.GetLogger()

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Warnw("登出时获取用户信息失败", "error", err)
		// 即使获取用户信息失败也返回成功，让前端清除token
	}

	// TODO: 如果使用Redis或数据库存储token黑名单，在这里添加逻辑
	// 目前 JWT 是无状态的，主要靠客户端删除token

	logger.Infow("用户登出", "userID", user.ID, "username", user.Username)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("登出成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*AuthPayload, error) {
	logger := middleware.GetLogger()

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("刷新token时获取用户信息失败", "error", err)
		return nil, err
	}

	// 生成新的token
	token, err := models.GenerateJWT(user.ID, user.Username, user.Role, false)
	if err != nil {
		logger.Errorw("生成新token失败", "error", err)
		return nil, models.ErrInternalServerError
	}

	// 生成新的刷新token
	refreshToken, err := models.GenerateJWT(user.ID, user.Username, user.Role, true)
	if err != nil {
		logger.Errorw("生成新刷新token失败", "error", err)
		refreshToken = "" // 如果失败就不返回刷新token
	}

	logger.Infow("刷新token成功", "userID", user.ID, "username", user.Username)

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    time.Now().Add(24 * time.Hour),
	}, nil
}

// SendVerificationCode is the resolver for the sendVerificationCode field.
func (r *mutationResolver) SendVerificationCode(ctx context.Context, email string, typeArg VerificationType) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	authService := services.NewAuthService(r.DB)

	logger.Infow("开始发送验证码", "email", email, "type", typeArg)

	var err error
	switch typeArg {
	case VerificationTypeRegister:
		// 注册验证码 - 检查邮箱是否已存在
		var user models.User
		if dbErr := r.DB.Where("email = ?", email).First(&user).Error; dbErr == nil {
			return &GeneralResponse{
				Success: false,
				Message: strPtr("该邮箱已被注册"),
				Code:    strPtr("EMAIL_EXISTS"),
			}, nil
		}
		err = authService.SendEmailLoginCode(email)
	case VerificationTypeLogin:
		err = authService.SendEmailLoginCode(email)
	case VerificationTypeResetPassword:
		err = authService.RequestPasswordReset(email)
	default:
		return &GeneralResponse{
			Success: false,
			Message: strPtr("不支持的验证类型"),
			Code:    strPtr("INVALID_TYPE"),
		}, nil
	}

	if err != nil {
		logger.Errorw("发送验证码失败", "error", err, "email", email, "type", typeArg)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("发送验证码失败"),
			Code:    strPtr("SEND_CODE_FAILED"),
		}, nil
	}

	logger.Infow("验证码发送成功", "email", email, "type", typeArg)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("验证码已发送到您的邮箱"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input VerifyEmailInput) (*GeneralResponse, error) {
	logger := middleware.GetLogger()

	logger.Infow("开始验证邮箱", "email", input.Email, "type", input.Type)

	// TODO: 实现邮箱验证逻辑，目前这个功能在 VerifyEmailAndLogin 中实现
	// 这里可以调用认证服务进行验证

	logger.Infow("邮箱验证成功", "email", input.Email)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("邮箱验证成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input RequestPasswordResetInput) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	authService := services.NewAuthService(r.DB)

	logger.Infow("开始请求密码重置", "email", input.Email)

	// 调用认证服务
	err := authService.RequestPasswordReset(input.Email)
	if err != nil {
		logger.Errorw("请求密码重置失败", "error", err, "email", input.Email)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("发送重置邮件失败"),
			Code:    strPtr("SEND_RESET_FAILED"),
		}, nil
	}

	logger.Infow("密码重置邮件发送成功", "email", input.Email)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码重置邮件已发送到您的邮箱"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// ConfirmPasswordReset is the resolver for the confirmPasswordReset field.
func (r *mutationResolver) ConfirmPasswordReset(ctx context.Context, input ConfirmPasswordResetInput) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	authService := services.NewAuthService(r.DB)

	logger.Infow("开始确认密码重置", "token", input.Token)

	// 调用认证服务
	err := authService.ConfirmPasswordReset(input.Token, input.NewPassword)
	if err != nil {
		logger.Errorw("确认密码重置失败", "error", err, "token", input.Token)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("密码重置失败"),
			Code:    strPtr("RESET_FAILED"),
		}, nil
	}

	logger.Infow("密码重置成功")

	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码重置成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input UpdateProfileInput) (*User, error) {
	logger := middleware.GetLogger()
	userService := services.NewUserService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("更新用户个人资料时获取用户信息失败", "error", err)
		return nil, err
	}

	// 转换输入
	updateInput := &models.UpdateProfileInput{
		Username: input.Username,
	}

	logger.Infow("开始更新用户个人资料", "userID", user.ID, "username", user.Username)

	// 调用用户服务
	updatedUser, err := userService.UpdateProfile(user.ID, updateInput)
	if err != nil {
		logger.Errorw("更新用户个人资料失败", "error", err, "userID", user.ID)
		return nil, err
	}

	logger.Infow("更新用户个人资料成功", "userID", updatedUser.ID)

	return convertToGraphQLUser(updatedUser), nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, currentPassword string, newPassword string) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	userService := services.NewUserService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("修改密码时获取用户信息失败", "error", err)
		return nil, err
	}

	logger.Infow("开始修改密码", "userID", user.ID, "username", user.Username)

	// 调用用户服务
	err = userService.ChangePassword(user.ID, currentPassword, newPassword)
	if err != nil {
		logger.Errorw("修改密码失败", "error", err, "userID", user.ID)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("修改密码失败"),
			Code:    strPtr("CHANGE_PASSWORD_FAILED"),
		}, nil
	}

	logger.Infow("修改密码成功", "userID", user.ID)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码修改成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input CreatePostInput) (*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("创建文章时获取用户信息失败", "error", err)
		return nil, err
	}

	// 转换输入
	createInput := &models.CreatePostInput{
		Title:      input.Title,
		Content:    input.Content,
		Tags:       input.Tags,
		Categories: input.Categories,
	}

	// 设置可选字段
	if input.CoverImageURL != nil {
		createInput.CoverImageURL = input.CoverImageURL
	}
	if input.AccessLevel != nil {
		createInput.AccessLevel = string(*input.AccessLevel)
	} else {
		createInput.AccessLevel = "PUBLIC"
	}

	logger.Infow("开始创建文章", "userID", user.ID, "title", input.Title)

	// 调用博客服务
	post, err := blogService.CreatePost(createInput, user.ID)
	if err != nil {
		logger.Errorw("创建文章失败", "error", err, "userID", user.ID, "title", input.Title)
		return nil, err
	}

	logger.Infow("创建文章成功", "postID", post.ID, "title", post.Title, "userID", user.ID)

	return convertToGraphQLBlogPost(post), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input UpdatePostInput) (*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("更新文章时获取用户信息失败", "error", err)
		return nil, err
	}

	// 解析ID
	postID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的文章ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	// 转换输入
	updateInput := &models.UpdatePostInput{
		Title:         input.Title,
		Content:       input.Content,
		Tags:          input.Tags,
		Categories:    input.Categories,
		CoverImageURL: input.CoverImageURL,
	}

	if input.AccessLevel != nil {
		accessLevel := string(*input.AccessLevel)
		updateInput.AccessLevel = &accessLevel
	}

	logger.Infow("开始更新文章", "postID", postID, "userID", user.ID)

	// 调用博客服务
	post, err := blogService.UpdatePost(postID, updateInput, user.ID, user.Role)
	if err != nil {
		logger.Errorw("更新文章失败", "error", err, "postID", postID, "userID", user.ID)
		return nil, err
	}

	logger.Infow("更新文章成功", "postID", post.ID, "title", post.Title, "userID", user.ID)

	return convertToGraphQLBlogPost(post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("删除文章时获取用户信息失败", "error", err)
		return nil, err
	}

	// 解析ID
	postID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的文章ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始删除文章", "postID", postID, "userID", user.ID)

	// 调用博客服务
	err = blogService.DeletePost(postID, user.ID, user.Role)
	if err != nil {
		logger.Errorw("删除文章失败", "error", err, "postID", postID, "userID", user.ID)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("删除文章失败"),
			Code:    strPtr("DELETE_FAILED"),
		}, nil
	}

	logger.Infow("删除文章成功", "postID", postID, "userID", user.ID)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("文章已删除"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// PublishPost is the resolver for the publishPost field.
func (r *mutationResolver) PublishPost(ctx context.Context, id string) (*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("发布文章时获取用户信息失败", "error", err)
		return nil, err
	}

	// 解析ID
	postID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的文章ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始发布文章", "postID", postID, "userID", user.ID)

	// 调用博客服务
	post, err := blogService.PublishPost(postID, user.ID, user.Role)
	if err != nil {
		logger.Errorw("发布文章失败", "error", err, "postID", postID, "userID", user.ID)
		return nil, err
	}

	logger.Infow("发布文章成功", "postID", post.ID, "title", post.Title, "userID", user.ID)

	return convertToGraphQLBlogPost(post), nil
}

// ArchivePost is the resolver for the archivePost field.
func (r *mutationResolver) ArchivePost(ctx context.Context, id string) (*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("归档文章时获取用户信息失败", "error", err)
		return nil, err
	}

	// 解析ID
	postID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的文章ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始归档文章", "postID", postID, "userID", user.ID)

	// 调用博客服务
	post, err := blogService.ArchivePost(postID, user.ID, user.Role)
	if err != nil {
		logger.Errorw("归档文章失败", "error", err, "postID", postID, "userID", user.ID)
		return nil, err
	}

	logger.Infow("归档文章成功", "postID", post.ID, "title", post.Title, "userID", user.ID)

	return convertToGraphQLBlogPost(post), nil
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, id string) (*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("点赞文章时获取用户信息失败", "error", err)
		return nil, err
	}

	// 解析ID
	postID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的文章ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始点赞文章", "postID", postID, "userID", user.ID)

	// 调用博客服务
	post, err := blogService.LikePost(postID, user.ID)
	if err != nil {
		logger.Errorw("点赞文章失败", "error", err, "postID", postID, "userID", user.ID)
		return nil, err
	}

	logger.Infow("点赞文章成功", "postID", post.ID, "title", post.Title, "userID", user.ID)

	return convertToGraphQLBlogPost(post), nil
}

// UnlikePost is the resolver for the unlikePost field.
func (r *mutationResolver) UnlikePost(ctx context.Context, id string) (*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("取消点赞文章时获取用户信息失败", "error", err)
		return nil, err
	}

	// 解析ID
	postID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的文章ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始取消点赞文章", "postID", postID, "userID", user.ID)

	// 调用博客服务
	post, err := blogService.UnlikePost(postID, user.ID)
	if err != nil {
		logger.Errorw("取消点赞文章失败", "error", err, "postID", postID, "userID", user.ID)
		return nil, err
	}

	logger.Infow("取消点赞文章成功", "postID", post.ID, "title", post.Title, "userID", user.ID)

	return convertToGraphQLBlogPost(post), nil
}

// UploadImage is the resolver for the uploadImage field.
func (r *mutationResolver) UploadImage(ctx context.Context, file graphql.Upload) (*ImageUploadResponse, error) {
	logger := middleware.GetLogger()

	// 需要用户登录
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("上传图片需要登录", "error", err)
		return nil, err
	}

	logger.Infow("用户开始上传图片", "userID", user.ID, "filename", file.Filename)

	// TODO: 实现文件上传逻辑
	// 1. 验证文件类型和大小
	// 2. 生成唯一文件名
	// 3. 保存到本地或云存储
	// 4. 返回文件URL

	// 目前返回模拟的成功响应
	mockURL := "https://example.com/uploads/" + file.Filename

	logger.Infow("图片上传模拟成功", "userID", user.ID, "filename", file.Filename, "url", mockURL)

	return &ImageUploadResponse{
		ImageURL:  mockURL,
		Filename:  file.Filename,
		Size:      int(file.Size), // file.Size 是 int64，需要转换
		DeleteURL: nil,            // 简化实现，不提供删除URL
	}, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, input CreateFolderInput) (*FileFolder, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("创建文件夹需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始创建文件夹", "name", input.Name)

	// 调用文件服务
	folder, err := fileService.CreateFolder(input.Name)
	if err != nil {
		logger.Errorw("创建文件夹失败", "error", err, "name", input.Name)
		return nil, err
	}

	logger.Infow("创建文件夹成功", "name", input.Name, "path", folder.Path)

	// 转换为 GraphQL 类型
	return &FileFolder{
		Name:      folder.Name,
		Path:      folder.Path,
		CreatedAt: folder.CreatedAt,
		FileCount: folder.FileCount,
	}, nil
}

// UploadMarkdownFile is the resolver for the uploadMarkdownFile field.
func (r *mutationResolver) UploadMarkdownFile(ctx context.Context, input UploadMarkdownFileInput) (*FileUploadResponse, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("上传文件需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始上传 Markdown 文件", "folder", input.Folder, "title", input.Title)

	// 从 GraphQL Upload 中读取文件内容
	upload := input.File
	file := upload.File
	if file == nil {
		logger.Errorw("上传文件为空")
		return nil, fmt.Errorf("上传文件为空")
	}

	// 读取文件内容
	content := make([]byte, upload.Size)
	_, err = file.Read(content)
	if err != nil {
		logger.Errorw("读取上传文件内容失败", "error", err)
		return nil, fmt.Errorf("读取上传文件内容失败")
	}

	// 调用文件服务
	result, err := fileService.UploadMarkdownFile(content, input.Folder, input.Title)
	if err != nil {
		logger.Errorw("上传 Markdown 文件失败", "error", err, "folder", input.Folder, "title", input.Title)
		return nil, err
	}

	logger.Infow("上传 Markdown 文件成功", "folder", input.Folder, "title", input.Title, "fileName", result.FileName)

	// 转换为 GraphQL 类型
	return &FileUploadResponse{
		Success:  result.Success,
		Message:  result.Message,
		FilePath: &result.FilePath,
		FileName: &result.FileName,
	}, nil
}

// UpdateFile is the resolver for the updateFile field.
func (r *mutationResolver) UpdateFile(ctx context.Context, input UpdateFileInput) (*MarkdownFile, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("更新文件需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始更新文件", "folder", input.Folder, "fileName", input.FileName, "contentLength", len(input.Content))

	// 调用文件服务
	file, err := fileService.UpdateFile(input.Folder, input.FileName, input.Content)
	if err != nil {
		logger.Errorw("更新文件失败", "error", err, "folder", input.Folder, "fileName", input.FileName)
		return nil, err
	}

	logger.Infow("更新文件成功", "folder", input.Folder, "fileName", input.FileName, "size", file.Size)

	// 转换为 GraphQL 类型
	return &MarkdownFile{
		Name:      file.Name,
		Folder:    file.Folder,
		Content:   &file.Content,
		Size:      int(file.Size),
		CreatedAt: file.CreatedAt,
		UpdatedAt: file.UpdatedAt,
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, folder string, fileName string) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("删除文件需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始删除文件", "folder", folder, "fileName", fileName)

	// 调用文件服务
	err = fileService.DeleteFile(folder, fileName)
	if err != nil {
		logger.Errorw("删除文件失败", "error", err, "folder", folder, "fileName", fileName)
		return &GeneralResponse{
			Success: false,
			Message: strPtr(err.Error()),
			Code:    strPtr("DELETE_FILE_FAILED"),
		}, nil
	}

	logger.Infow("删除文件成功", "folder", folder, "fileName", fileName)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("文件删除成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, name string) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("删除文件夹需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始删除文件夹", "name", name)

	// 调用文件服务
	err = fileService.DeleteFolder(name)
	if err != nil {
		logger.Errorw("删除文件夹失败", "error", err, "name", name)
		return &GeneralResponse{
			Success: false,
			Message: strPtr(err.Error()),
			Code:    strPtr("DELETE_FOLDER_FAILED"),
		}, nil
	}

	logger.Infow("删除文件夹成功", "name", name)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("文件夹删除成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// AdminCreateUser is the resolver for the adminCreateUser field.
func (r *mutationResolver) AdminCreateUser(ctx context.Context, input AdminCreateUserInput) (*User, error) {
	logger := middleware.GetLogger()
	adminService := services.NewAdminService(r.DB)

	// 需要管理员权限
	user, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("创建用户需要管理员权限", "error", err)
		return nil, err
	}

	// 转换输入
	createInput := &models.AdminCreateUserInput{
		Username:   input.Username,
		Email:      input.Email,
		Password:   input.Password,
		IsVerified: false,
	}

	if input.Role != nil {
		createInput.Role = models.UserRole(*input.Role)
	} else {
		createInput.Role = "user"
	}

	if input.IsVerified != nil {
		createInput.IsVerified = *input.IsVerified
	}

	logger.Infow("管理员开始创建用户", "adminID", user.ID, "username", input.Username, "email", input.Email)

	// 调用管理员服务
	newUser, err := adminService.CreateUser(createInput)
	if err != nil {
		logger.Errorw("管理员创建用户失败", "error", err, "adminID", user.ID, "username", input.Username)
		return nil, err
	}

	logger.Infow("管理员创建用户成功", "adminID", user.ID, "newUserID", newUser.ID, "username", newUser.Username)

	return convertToGraphQLUser(newUser), nil
}

// AdminUpdateUser is the resolver for the adminUpdateUser field.
func (r *mutationResolver) AdminUpdateUser(ctx context.Context, id string, username *string, email *string, role *UserRole, isVerified *bool, isActive *bool) (*User, error) {
	logger := middleware.GetLogger()
	adminService := services.NewAdminService(r.DB)

	// 需要管理员权限
	adminUser, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("更新用户需要管理员权限", "error", err)
		return nil, err
	}

	// 解析ID
	userID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的用户ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	// 转换role为字符串
	var roleStr *string
	if role != nil {
		roleValue := string(*role)
		roleStr = &roleValue
	}

	logger.Infow("管理员开始更新用户", "adminID", adminUser.ID, "targetUserID", userID)

	// 调用管理员服务
	updatedUser, err := adminService.UpdateUser(userID, username, email, roleStr, isVerified, isActive)
	if err != nil {
		logger.Errorw("管理员更新用户失败", "error", err, "adminID", adminUser.ID, "targetUserID", userID)
		return nil, err
	}

	logger.Infow("管理员更新用户成功", "adminID", adminUser.ID, "targetUserID", updatedUser.ID, "username", updatedUser.Username)

	return convertToGraphQLUser(updatedUser), nil
}

// AdminDeleteUser is the resolver for the adminDeleteUser field.
func (r *mutationResolver) AdminDeleteUser(ctx context.Context, id string) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	adminService := services.NewAdminService(r.DB)

	// 需要管理员权限
	adminUser, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("删除用户需要管理员权限", "error", err)
		return nil, err
	}

	// 解析ID
	userID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的用户ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("管理员开始删除用户", "adminID", adminUser.ID, "targetUserID", userID)

	// 调用管理员服务
	err = adminService.DeleteUser(userID)
	if err != nil {
		logger.Errorw("管理员删除用户失败", "error", err, "adminID", adminUser.ID, "targetUserID", userID)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("删除用户失败"),
			Code:    strPtr("DELETE_USER_FAILED"),
		}, nil
	}

	logger.Infow("管理员删除用户成功", "adminID", adminUser.ID, "targetUserID", userID)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("用户已删除"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// CreateInviteCode is the resolver for the createInviteCode field.
func (r *mutationResolver) CreateInviteCode(ctx context.Context, input CreateInviteCodeInput) (*InviteCode, error) {
	logger := middleware.GetLogger()
	inviteCodeService := services.NewInviteCodeService(r.DB)

	// 需要管理员权限
	user, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("创建邀请码需要管理员权限", "error", err)
		return nil, err
	}

	// 转换输入
	createInput := &models.CreateInviteCodeInput{
		ExpiresAt:   input.ExpiresAt,
		MaxUses:     1, // 默认值
		Description: "",
	}

	if input.MaxUses != nil {
		createInput.MaxUses = *input.MaxUses
	}

	if input.Description != nil {
		createInput.Description = *input.Description
	}

	logger.Infow("开始创建邀请码", "userID", user.ID, "maxUses", createInput.MaxUses)

	// 调用邀请码服务
	inviteCode, err := inviteCodeService.CreateInviteCode(user.ID, createInput)
	if err != nil {
		logger.Errorw("创建邀请码失败", "error", err, "userID", user.ID)
		return nil, err
	}

	logger.Infow("创建邀请码成功", "userID", user.ID, "inviteCodeID", inviteCode.ID, "code", inviteCode.Code)

	return convertToGraphQLInviteCode(inviteCode), nil
}

// DeactivateInviteCode is the resolver for the deactivateInviteCode field.
func (r *mutationResolver) DeactivateInviteCode(ctx context.Context, id string) (*GeneralResponse, error) {
	logger := middleware.GetLogger()
	inviteCodeService := services.NewInviteCodeService(r.DB)

	// 需要管理员权限
	user, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("停用邀请码需要管理员权限", "error", err)
		return nil, err
	}

	// 解析ID
	inviteCodeID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的邀请码ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始停用邀请码", "userID", user.ID, "inviteCodeID", inviteCodeID)

	// 调用邀请码服务
	err = inviteCodeService.DeactivateInviteCode(inviteCodeID)
	if err != nil {
		logger.Errorw("停用邀请码失败", "error", err, "userID", user.ID, "inviteCodeID", inviteCodeID)
		return &GeneralResponse{
			Success: false,
			Message: strPtr("停用邀请码失败"),
			Code:    strPtr("DEACTIVATE_INVITE_CODE_FAILED"),
		}, nil
	}

	logger.Infow("停用邀请码成功", "userID", user.ID, "inviteCodeID", inviteCodeID)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("邀请码已停用"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// ClearCache is the resolver for the clearCache field.
func (r *mutationResolver) ClearCache(ctx context.Context) (*GeneralResponse, error) {
	logger := middleware.GetLogger()

	// 需要管理员权限
	user, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("清理缓存需要管理员权限", "error", err)
		return nil, err
	}

	logger.Infow("管理员开始清理缓存", "adminID", user.ID)

	// 实现缓存清理逻辑
	models.GetCache().Clear() // 清理内存缓存

	// 记录缓存清理操作
	middleware.GetLogger().Infow("缓存清理操作完成", "adminID", user.ID, "timestamp", time.Now())

	logger.Infow("缓存清理完成", "adminID", user.ID)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("缓存已清理"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// RebuildSearchIndex is the resolver for the rebuildSearchIndex field.
func (r *mutationResolver) RebuildSearchIndex(ctx context.Context) (*GeneralResponse, error) {
	logger := middleware.GetLogger()

	// 需要管理员权限
	user, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("重建搜索索引需要管理员权限", "error", err)
		return nil, err
	}

	logger.Infow("管理员开始重建搜索索引", "adminID", user.ID)

	// 实现搜索索引重建逻辑
	// 重建搜索索引（重新计算所有文章相关性）
	var posts []models.BlogPost
	err = r.DB.Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'").Find(&posts).Error
	if err != nil {
		logger.Errorw("获取文章列表失败", "error", err)
		return nil, fmt.Errorf("重建索引失败")
	}

	// 模拟索引重建过程
	for i, post := range posts {
		// 更新文章搜索相关数据
		if post.Excerpt == "" && len(post.Content) > 200 {
			posts[i].Excerpt = post.Content[:200] + "..."
			r.DB.Save(&posts[i])
		}
	}

	logger.Infow("搜索索引重建完成", "adminID", user.ID, "processedPosts", len(posts))

	logger.Infow("搜索索引重建完成", "adminID", user.ID)

	return &GeneralResponse{
		Success: true,
		Message: strPtr("搜索索引重建完成"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	logger := middleware.GetLogger()

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("获取当前用户信息失败", "error", err)
		return nil, err
	}

	logger.Infow("获取当前用户信息成功", "userID", user.ID, "username", user.Username)

	return convertToGraphQLUser(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	logger := middleware.GetLogger()
	userService := services.NewUserService(r.DB)

	// 解析ID
	userID, err := parseID(id)
	if err != nil {
		logger.Errorw("无效的用户ID", "error", err, "id", id)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始获取用户信息", "userID", userID)

	// 调用用户服务
	user, err := userService.GetUserByID(userID)
	if err != nil {
		logger.Errorw("获取用户信息失败", "error", err, "userID", userID)
		return nil, err
	}

	logger.Infow("获取用户信息成功", "userID", user.ID, "username", user.Username)

	return convertToGraphQLUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int, search *string, role *UserRole, isVerified *bool) ([]*User, error) {
	logger := middleware.GetLogger()
	userService := services.NewUserService(r.DB)

	// 需要管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("获取用户列表需要管理员权限", "error", err)
		return nil, err
	}

	// 设置默认值
	if limit == nil {
		limitVal := 10
		limit = &limitVal
	}
	if offset == nil {
		offsetVal := 0
		offset = &offsetVal
	}

	logger.Infow("开始获取用户列表", "limit", *limit, "offset", *offset)

	// 调用用户服务
	users, err := userService.GetUsers(*limit, *offset, "", "", nil)
	if err != nil {
		logger.Errorw("获取用户列表失败", "error", err)
		return nil, err
	}

	logger.Infow("获取用户列表成功", "count", len(users))

	// 转换为 GraphQL 类型
	result := make([]*User, len(users))
	for i, user := range users {
		result[i] = convertToGraphQLUser(user)
	}

	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id *string, slug *string) (*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户（可选）
	user, _ := getUserFromContext(ctx, r.DB)
	var userID *uint
	var userRole = "user"
	if user != nil {
		userID = &user.ID
		userRole = user.Role
	}

	var post *models.BlogPost
	var err error

	if id != nil {
		// 根据ID查找
		postIDParsed, parseErr := parseID(*id)
		if parseErr != nil {
			logger.Errorw("无效的文章ID", "error", parseErr, "id", *id)
			return nil, ErrInvalidInput
		}

		logger.Infow("开始根据ID获取文章", "postID", postIDParsed)
		post, err = blogService.GetPostByID(postIDParsed, userID, userRole)
	} else if slug != nil {
		// 根据slug查找
		logger.Infow("开始根据slug获取文章", "slug", *slug)
		post, err = blogService.GetPostBySlug(*slug, userID, userRole)
	} else {
		logger.Errorw("必须提供id或slug参数")
		return nil, ErrInvalidInput
	}

	if err != nil {
		logger.Errorw("获取文章失败", "error", err)
		return nil, err
	}

	logger.Infow("获取文章成功", "postID", post.ID, "title", post.Title)

	return convertToGraphQLBlogPost(post), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int, offset *int, filter *PostFilterInput, sort *PostSortInput) ([]*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户（可选）
	user, _ := getUserFromContext(ctx, r.DB)
	var userID *uint
	var userRole = "user"
	if user != nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 设置默认值
	if limit == nil {
		limitVal := 10
		limit = &limitVal
	}
	if offset == nil {
		offsetVal := 0
		offset = &offsetVal
	}

	// 转换过滤条件
	var blogFilter *services.PostFilter
	if filter != nil {
		blogFilter = &services.PostFilter{}
		if filter.AuthorID != nil {
			authorID, err := parseID(*filter.AuthorID)
			if err != nil {
				logger.Errorw("无效的作者ID", "error", err, "authorID", *filter.AuthorID)
				return nil, ErrInvalidInput
			}
			blogFilter.AuthorID = &authorID
		}
		if filter.Status != nil {
			status := string(*filter.Status)
			blogFilter.Status = &status
		}
		if filter.AccessLevel != nil {
			accessLevel := string(*filter.AccessLevel)
			blogFilter.AccessLevel = &accessLevel
		}
		blogFilter.Tags = filter.Tags
		blogFilter.Categories = filter.Categories
	}

	// 转换排序条件
	var blogSort *services.PostSort
	if sort != nil {
		blogSort = &services.PostSort{
			Field:     *sort.Field,
			Direction: *sort.Order,
		}
	}

	logger.Infow("开始获取文章列表", "limit", *limit, "offset", *offset)

	// 调用博客服务
	posts, err := blogService.GetPosts(*limit, *offset, blogFilter, blogSort, userID, userRole)
	if err != nil {
		logger.Errorw("获取文章列表失败", "error", err)
		return nil, err
	}

	logger.Infow("获取文章列表成功", "count", len(posts))

	// 转换为 GraphQL 类型
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPost(post)
	}

	return result, nil
}

// PostVersions is the resolver for the postVersions field.
func (r *queryResolver) PostVersions(ctx context.Context, postID string) ([]*BlogPostVersion, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户
	user, err := requireAuth(ctx, r.DB)
	if err != nil {
		logger.Errorw("获取文章版本历史时获取用户信息失败", "error", err)
		return nil, err
	}

	// 解析ID
	postIDParsed, err := parseID(postID)
	if err != nil {
		logger.Errorw("无效的文章ID", "error", err, "postID", postID)
		return nil, ErrInvalidInput
	}

	logger.Infow("开始获取文章版本历史", "postID", postIDParsed, "userID", user.ID)

	// 调用博客服务
	versions, err := blogService.GetPostVersions(postIDParsed, user.ID, user.Role)
	if err != nil {
		logger.Errorw("获取文章版本历史失败", "error", err, "postID", postIDParsed, "userID", user.ID)
		return nil, err
	}

	logger.Infow("获取文章版本历史成功", "postID", postIDParsed, "count", len(versions))

	// 转换为 GraphQL 类型
	result := make([]*BlogPostVersion, len(versions))
	for i, version := range versions {
		result[i] = convertToGraphQLBlogPostVersion(version)
	}

	return result, nil
}

// SearchPosts is the resolver for the searchPosts field.
func (r *queryResolver) SearchPosts(ctx context.Context, query string, limit *int, offset *int) (*SearchResult, error) {
	logger := middleware.GetLogger()
	searchService := services.NewSearchService(r.DB)

	// 获取当前用户（可选）
	user, _ := getUserFromContext(ctx, r.DB)
	var userID *uint
	var userRole = "user"
	if user != nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 设置默认值
	if limit == nil {
		limitVal := 10
		limit = &limitVal
	}
	if offset == nil {
		offsetVal := 0
		offset = &offsetVal
	}

	logger.Infow("开始高级搜索文章", "query", query, "limit", *limit, "offset", *offset)

	// 使用高级搜索服务
	searchResult, err := searchService.AdvancedSearchPosts(query, *limit, *offset, userID, userRole)
	if err != nil {
		logger.Errorw("高级搜索文章失败", "error", err, "query", query)
		return nil, err
	}

	logger.Infow("高级搜索文章成功", "query", query, "count", len(searchResult.Posts), "total", searchResult.Total, "took", searchResult.Took)

	// 转换为 GraphQL 类型
	resultPosts := make([]*BlogPost, len(searchResult.Posts))
	for i, post := range searchResult.Posts {
		resultPosts[i] = convertToGraphQLBlogPost(post)
	}

	return &SearchResult{
		Posts: resultPosts,
		Total: int(searchResult.Total),
		Took:  searchResult.Took.String(),
	}, nil
}

// GetSearchSuggestions is the resolver for the getSearchSuggestions field.
func (r *queryResolver) GetSearchSuggestions(ctx context.Context, query string, limit *int) ([]string, error) {
	panic(fmt.Errorf("not implemented: GetSearchSuggestions - getSearchSuggestions"))
}

// GetTrendingSearches is the resolver for the getTrendingSearches field.
func (r *queryResolver) GetTrendingSearches(ctx context.Context, limit *int) ([]string, error) {
	panic(fmt.Errorf("not implemented: GetTrendingSearches - getTrendingSearches"))
}

// GetSearchStats is the resolver for the getSearchStats field.
func (r *queryResolver) GetSearchStats(ctx context.Context) (*SearchStats, error) {
	panic(fmt.Errorf("not implemented: GetSearchStats - getSearchStats"))
}

// InviteCodes is the resolver for the inviteCodes field.
func (r *queryResolver) InviteCodes(ctx context.Context, limit *int, offset *int, isActive *bool) ([]*InviteCode, error) {
	logger := middleware.GetLogger()
	inviteCodeService := services.NewInviteCodeService(r.DB)

	// 需要管理员权限
	user, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("查看邀请码列表需要管理员权限", "error", err)
		return nil, err
	}

	// 设置默认值
	if limit == nil {
		limitVal := 20
		limit = &limitVal
	}
	if offset == nil {
		offsetVal := 0
		offset = &offsetVal
	}

	logger.Infow("管理员开始获取邀请码列表", "adminID", user.ID, "limit", *limit, "offset", *offset)

	// 调用邀请码服务
	inviteCodes, err := inviteCodeService.GetInviteCodes(*limit, *offset, isActive)
	if err != nil {
		logger.Errorw("获取邀请码列表失败", "error", err, "adminID", user.ID)
		return nil, err
	}

	logger.Infow("获取邀请码列表成功", "adminID", user.ID, "count", len(inviteCodes))

	// 转换为 GraphQL 类型
	result := make([]*InviteCode, len(inviteCodes))
	for i, inviteCode := range inviteCodes {
		result[i] = convertToGraphQLInviteCode(inviteCode)
	}

	return result, nil
}

// ServerDashboard is the resolver for the serverDashboard field.
func (r *queryResolver) ServerDashboard(ctx context.Context) (*ServerDashboard, error) {
	logger := middleware.GetLogger()
	adminService := services.NewAdminService(r.DB)

	// 需要管理员权限
	user, err := requireAdmin(ctx, r.DB)
	if err != nil {
		logger.Errorw("查看服务器仪表盘需要管理员权限", "error", err)
		return nil, err
	}

	logger.Infow("管理员开始查看服务器仪表盘", "adminID", user.ID)

	// 调用管理员服务获取基础数据
	basicDashboard, err := adminService.GetServerDashboard()
	if err != nil {
		logger.Errorw("获取服务器仪表盘数据失败", "error", err, "adminID", user.ID)
		return nil, err
	}

	// 获取系统信息
	hostname, _ := os.Hostname()
	goVersion := runtime.Version()
	cpuCount := runtime.NumCPU()
	goroutines := runtime.NumGoroutine()

	// 获取内存信息
	var m runtime.MemStats
	runtime.ReadMemStats(&m)

	memory := &ServerMemoryStats{
		Alloc:      fmt.Sprintf("%.2f MB", float64(m.Alloc)/1024/1024),
		TotalAlloc: fmt.Sprintf("%.2f MB", float64(m.TotalAlloc)/1024/1024),
		Sys:        fmt.Sprintf("%.2f MB", float64(m.Sys)/1024/1024),
		HeapAlloc:  fmt.Sprintf("%.2f MB", float64(m.HeapAlloc)/1024/1024),
		HeapSys:    fmt.Sprintf("%.2f MB", float64(m.HeapSys)/1024/1024),
	}

	uptime := getUptime()

	dashboard := &ServerDashboard{
		ServerTime:         time.Now(),
		Hostname:           hostname,
		GoVersion:          goVersion,
		CPUCount:           cpuCount,
		Goroutines:         goroutines,
		Memory:             memory,
		Uptime:             uptime,
		UserCount:          basicDashboard.UserCount,
		PostCount:          basicDashboard.PostCount,
		TodayRegistrations: basicDashboard.TodayRegistrations,
		TodayPosts:         basicDashboard.TodayPosts,
	}

	logger.Infow("获取服务器仪表盘成功", "adminID", user.ID)

	return dashboard, nil
}

// GetPopularPosts is the resolver for the getPopularPosts field.
func (r *queryResolver) GetPopularPosts(ctx context.Context, limit *int) ([]*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户（可选）
	user, _ := getUserFromContext(ctx, r.DB)
	var userID *uint
	var userRole = "user"
	if user != nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 设置默认值
	if limit == nil {
		limitVal := 10
		limit = &limitVal
	}

	logger.Infow("开始获取热门文章", "limit", *limit)

	// 调用博客服务
	posts, err := blogService.GetPopularPosts(*limit, userID, userRole)
	if err != nil {
		logger.Errorw("获取热门文章失败", "error", err)
		return nil, err
	}

	logger.Infow("获取热门文章成功", "count", len(posts))

	// 转换为 GraphQL 类型
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPost(post)
	}

	return result, nil
}

// GetRecentPosts is the resolver for the getRecentPosts field.
func (r *queryResolver) GetRecentPosts(ctx context.Context, limit *int) ([]*BlogPost, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 获取当前用户（可选）
	user, _ := getUserFromContext(ctx, r.DB)
	var userID *uint
	var userRole = "user"
	if user != nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 设置默认值
	if limit == nil {
		limitVal := 10
		limit = &limitVal
	}

	logger.Infow("开始获取最新文章", "limit", *limit)

	// 调用博客服务
	posts, err := blogService.GetRecentPosts(*limit, userID, userRole)
	if err != nil {
		logger.Errorw("获取最新文章失败", "error", err)
		return nil, err
	}

	logger.Infow("获取最新文章成功", "count", len(posts))

	// 转换为 GraphQL 类型
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPost(post)
	}

	return result, nil
}

// GetTrendingTags is the resolver for the getTrendingTags field.
func (r *queryResolver) GetTrendingTags(ctx context.Context, limit *int) ([]string, error) {
	logger := middleware.GetLogger()
	blogService := services.NewBlogService(r.DB)

	// 设置默认值
	if limit == nil {
		limitVal := 10
		limit = &limitVal
	}

	logger.Infow("开始获取热门标签", "limit", *limit)

	// 调用博客服务
	tags, err := blogService.GetTrendingTags(*limit)
	if err != nil {
		logger.Errorw("获取热门标签失败", "error", err)
		return nil, err
	}

	logger.Infow("获取热门标签成功", "count", len(tags))

	return tags, nil
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context) ([]*FileFolder, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("获取文件夹列表需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始获取文件夹列表")

	// 调用文件服务
	folders, err := fileService.GetFolders()
	if err != nil {
		logger.Errorw("获取文件夹列表失败", "error", err)
		return nil, err
	}

	logger.Infow("获取文件夹列表成功", "count", len(folders))

	// 转换为 GraphQL 类型
	result := make([]*FileFolder, len(folders))
	for i, folder := range folders {
		result[i] = &FileFolder{
			Name:      folder.Name,
			Path:      folder.Path,
			CreatedAt: folder.CreatedAt,
			FileCount: folder.FileCount,
		}
	}

	return result, nil
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, folder string) ([]*MarkdownFile, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("获取文件列表需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始获取文件列表", "folder", folder)

	// 调用文件服务
	files, err := fileService.GetFiles(folder)
	if err != nil {
		logger.Errorw("获取文件列表失败", "error", err, "folder", folder)
		return nil, err
	}

	logger.Infow("获取文件列表成功", "folder", folder, "count", len(files))

	// 转换为 GraphQL 类型
	result := make([]*MarkdownFile, len(files))
	for i, file := range files {
		result[i] = &MarkdownFile{
			Name:      file.Name,
			Folder:    file.Folder,
			Size:      int(file.Size),
			CreatedAt: file.CreatedAt,
			UpdatedAt: file.UpdatedAt,
		}
	}

	return result, nil
}

// FileContent is the resolver for the fileContent field.
func (r *queryResolver) FileContent(ctx context.Context, folder string, fileName string) (*MarkdownFile, error) {
	logger := middleware.GetLogger()
	fileService := services.NewFileService()

	// 验证用户认证
	_, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		logger.Errorw("获取文件内容需要认证", "error", err)
		return nil, fmt.Errorf("未授权访问")
	}

	logger.Infow("开始获取文件内容", "folder", folder, "fileName", fileName)

	// 调用文件服务
	file, err := fileService.GetFileContent(folder, fileName)
	if err != nil {
		logger.Errorw("获取文件内容失败", "error", err, "folder", folder, "fileName", fileName)
		return nil, err
	}

	logger.Infow("获取文件内容成功", "folder", folder, "fileName", fileName, "size", file.Size)

	// 转换为 GraphQL 类型
	return &MarkdownFile{
		Name:      file.Name,
		Folder:    file.Folder,
		Content:   &file.Content,
		Size:      int(file.Size),
		CreatedAt: file.CreatedAt,
		UpdatedAt: file.UpdatedAt,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *blogPostResolver) IsLiked(ctx context.Context, obj *BlogPost) (bool, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.DB)
	if err != nil {
		// 如果用户未登录，返回false
		return false, nil
	}

	// 解析文章ID
	postID, err := parseID(obj.ID)
	if err != nil {
		return false, nil
	}

	// 查询用户是否点赞了该文章
	var like models.BlogPostLike
	err = r.DB.Where("blog_post_id = ? AND user_id = ?", postID, user.ID).First(&like).Error
	if err != nil {
		// 如果没找到记录，说明用户没有点赞
		return false, nil
	}

	return true, nil
}
type BlogPostResolver interface{}
func (r *Resolver) BlogPost() BlogPostResolver { return &blogPostResolver{r} }
type blogPostResolver struct{ *Resolver }
*/
