package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"fmt"
	"os"
	"repair-platform/middleware"
	"repair-platform/models"
	"repair-platform/services"
	"runtime"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"gorm.io/gorm"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*AuthPayload, error) {
	// 转换输入参数
	registerInput := &models.RegisterInput{
		Username:   input.Username,
		Email:      input.Email,
		Password:   input.Password,
		InviteCode: "",
	}

	if input.InviteCode != nil {
		registerInput.InviteCode = *input.InviteCode
	}

	// 调用认证服务
	authService := services.NewAuthService(r.Resolver.DB)
	user, token, err := authService.Register(registerInput)
	if err != nil {
		return nil, fmt.Errorf("注册失败: %w", err)
	}

	// 生成刷新令牌
	refreshToken := fmt.Sprintf("refresh_%d_%d", user.ID, time.Now().Unix())
	expiresAt := time.Now().Add(24 * time.Hour) // 默认24小时过期

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    expiresAt,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	// 转换输入参数
	loginInput := &models.LoginInput{
		Identifier: input.Identifier,
		Password:   input.Password,
		Remember:   false,
	}

	if input.Remember != nil {
		loginInput.Remember = *input.Remember
	}

	// 调用认证服务
	authService := services.NewAuthService(r.Resolver.DB)
	user, token, refreshToken, err := authService.LoginUser(loginInput)
	if err != nil {
		return nil, fmt.Errorf("登录失败: %w", err)
	}

	expiresAt := time.Now().Add(24 * time.Hour) // 默认24小时过期
	if loginInput.Remember {
		expiresAt = time.Now().Add(7 * 24 * time.Hour) // 记住我时7天过期
	}

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    expiresAt,
	}, nil
}

// EmailLogin is the resolver for the emailLogin field.
func (r *mutationResolver) EmailLogin(ctx context.Context, input EmailLoginInput) (*GeneralResponse, error) {
	// 检查邮箱格式
	if input.Email == "" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("邮箱地址不能为空"),
			Code:    strPtr("EMAIL_REQUIRED"),
		}, nil
	}

	// 检查用户是否存在
	var user models.User
	if err := r.Resolver.DB.Where("email = ?", input.Email).First(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return &GeneralResponse{
				Success: false,
				Message: strPtr("用户不存在"),
				Code:    strPtr("USER_NOT_FOUND"),
			}, nil
		}
		return nil, fmt.Errorf("数据库查询失败: %w", err)
	}

	// 生成验证码
	code, err := generateSecureCode()
	if err != nil {
		return nil, fmt.Errorf("生成验证码失败: %w", err)
	}

	// 存储验证码
	storeVerificationCode(input.Email, code)

	// 发送验证码邮件
	if err := sendVerificationCode(input.Email, code); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("发送验证码失败，请稍后重试"),
			Code:    strPtr("EMAIL_SEND_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("验证码已发送到您的邮箱"),
		Code:    strPtr("VERIFICATION_CODE_SENT"),
	}, nil
}

// VerifyEmailAndLogin is the resolver for the verifyEmailAndLogin field.
func (r *mutationResolver) VerifyEmailAndLogin(ctx context.Context, input VerifyEmailInput) (*AuthPayload, error) {
	// 检查邮箱格式
	if input.Email == "" {
		return nil, fmt.Errorf("邮箱地址不能为空")
	}

	// 检查验证码
	if input.Code == "" || len(input.Code) < 4 {
		return nil, fmt.Errorf("验证码格式错误")
	}

	// 验证验证码
	if !verifyCode(input.Email, input.Code) {
		return nil, fmt.Errorf("验证码错误或已过期")
	}

	// 查找用户
	var user models.User
	if err := r.Resolver.DB.Where("email = ?", input.Email).First(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("用户不存在")
		}
		return nil, fmt.Errorf("数据库查询失败: %w", err)
	}

	// 验证成功，删除验证码
	deleteVerificationCode(input.Email)
	
	// 生成JWT token
	token, err := models.GenerateJWT(user.ID, user.Username, user.Role, false)
	if err != nil {
		return nil, fmt.Errorf("生成token失败: %w", err)
	}

	// 生成刷新令牌
	refreshToken := fmt.Sprintf("refresh_%d_%d", user.ID, time.Now().Unix())
	expiresAt := time.Now().Add(24 * time.Hour)

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(&user),
		ExpiresAt:    expiresAt,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*GeneralResponse, error) {
	// Logout操作通常在前端清除JWT token即可，后端无需特殊处理
	// 这里返回成功响应
	return &GeneralResponse{
		Success: true,
		Message: strPtr("成功退出登录"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*AuthPayload, error) {
	// 从上下文获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 生成新的token
	token, err := models.GenerateJWT(user.ID, user.Username, user.Role, false)
	if err != nil {
		return nil, fmt.Errorf("生成token失败: %w", err)
	}

	// 生成新的刷新令牌
	refreshToken := fmt.Sprintf("refresh_%d_%d", user.ID, time.Now().Unix())
	expiresAt := time.Now().Add(24 * time.Hour)

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    expiresAt,
	}, nil
}

// SendVerificationCode is the resolver for the sendVerificationCode field.
func (r *mutationResolver) SendVerificationCode(ctx context.Context, email string, typeArg VerificationType) (*GeneralResponse, error) {
	// 简单实现：在实际生产中应该发送真实的验证码
	// 这里我们只是返回成功响应
	return &GeneralResponse{
		Success: true,
		Message: strPtr("验证码已发送"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input VerifyEmailInput) (*GeneralResponse, error) {
	// 简单实现：在实际生产中应该验证真实的验证码
	// 这里我们假设验证码总是正确的
	if len(input.Code) < 4 {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("验证码格式错误"),
			Code:    strPtr("INVALID_CODE"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("邮箱验证成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input RequestPasswordResetInput) (*GeneralResponse, error) {
	// 简化实现：发送密码重置邮件
	// 实际项目中需要：
	// 1. 验证邮箱格式
	// 2. 检查用户是否存在
	// 3. 生成重置token
	// 4. 发送重置邮件
	// 5. 存储重置token（设置过期时间）

	// 检查邮箱格式
	if input.Email == "" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("邮箱地址不能为空"),
			Code:    strPtr("EMAIL_REQUIRED"),
		}, nil
	}

	// 检查用户是否存在
	var user models.User
	if err := r.Resolver.DB.Where("email = ?", input.Email).First(&user).Error; err != nil {
		// 为了安全考虑，即使用户不存在也返回成功，避免邮箱枚举攻击
		return &GeneralResponse{
			Success: true,
			Message: strPtr("如果该邮箱存在，您将收到密码重置邮件"),
			Code:    strPtr("RESET_EMAIL_SENT"),
		}, nil
	}

	// 简化实现：直接返回成功
	// 实际项目中应该发送真实的重置邮件
	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码重置邮件已发送，请检查您的邮箱"),
		Code:    strPtr("RESET_EMAIL_SENT"),
	}, nil
}

// ConfirmPasswordReset is the resolver for the confirmPasswordReset field.
func (r *mutationResolver) ConfirmPasswordReset(ctx context.Context, input ConfirmPasswordResetInput) (*GeneralResponse, error) {
	// 简化实现：确认密码重置
	// 实际项目中需要：
	// 1. 验证重置token
	// 2. 检查token是否过期
	// 3. 验证新密码格式
	// 4. 更新用户密码
	// 5. 清除重置token

	// 检查输入参数
	if input.Token == "" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("重置令牌不能为空"),
			Code:    strPtr("TOKEN_REQUIRED"),
		}, nil
	}

	if input.NewPassword == "" || len(input.NewPassword) < 6 {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("新密码长度不能少于6位"),
			Code:    strPtr("PASSWORD_TOO_SHORT"),
		}, nil
	}

	// 简化实现：假设token总是有效的
	// 实际项目中应该验证存储的重置token
	
	// 简化实现：不进行实际的密码更新
	// 实际项目中应该：
	// 1. 根据token找到用户
	// 2. 加密新密码
	// 3. 更新数据库
	// 4. 清除重置token

	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码重置成功，请使用新密码登录"),
		Code:    strPtr("PASSWORD_RESET_SUCCESS"),
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input UpdateProfileInput) (*User, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 更新用户信息
	updates := map[string]interface{}{}

	if input.Username != nil {
		// 检查用户名是否已存在
		var existingUser models.User
		if err := r.Resolver.DB.Where("username = ? AND id != ?", *input.Username, user.ID).First(&existingUser).Error; err == nil {
			return nil, fmt.Errorf("用户名已存在")
		}
		updates["username"] = *input.Username
	}

	if input.Bio != nil {
		updates["bio"] = *input.Bio
	}

	if input.Avatar != nil {
		updates["avatar"] = *input.Avatar
	}

	// 如果没有更新内容，直接返回当前用户信息
	if len(updates) == 0 {
		return convertToGraphQLUser(user), nil
	}

	// 执行更新
	if err := r.Resolver.DB.Model(user).Updates(updates).Error; err != nil {
		return nil, fmt.Errorf("更新用户信息失败: %w", err)
	}

	// 重新加载用户信息
	if err := r.Resolver.DB.First(user, user.ID).Error; err != nil {
		return nil, fmt.Errorf("获取更新后的用户信息失败: %w", err)
	}

	return convertToGraphQLUser(user), nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, currentPassword string, newPassword string) (*GeneralResponse, error) {
	// 获取当前用户
	_, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 验证输入参数
	if currentPassword == "" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("当前密码不能为空"),
			Code:    strPtr("CURRENT_PASSWORD_REQUIRED"),
		}, nil
	}

	if newPassword == "" || len(newPassword) < 6 {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("新密码长度不能少于6位"),
			Code:    strPtr("PASSWORD_TOO_SHORT"),
		}, nil
	}

	// 简化实现：不验证当前密码
	// 实际项目中应该：
	// 1. 验证当前密码是否正确
	// 2. 检查新密码和当前密码是否相同
	// 3. 加密新密码
	// 4. 更新数据库
	
	// authService := services.NewAuthService(r.Resolver.DB)
	// if !authService.CheckPassword(user, currentPassword) {
	//     return &GeneralResponse{
	//         Success: false,
	//         Message: strPtr("当前密码错误"),
	//         Code:    strPtr("INVALID_CURRENT_PASSWORD"),
	//     }, nil
	// }

	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码修改成功"),
		Code:    strPtr("PASSWORD_CHANGED"),
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input CreatePostInput) (*BlogPost, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换输入参数
	createInput := &models.CreateBlogPostInput{
		Title:       input.Title,
		Content:     input.Content,
		AccessLevel: "PUBLIC", // 默认值
	}

	// 处理可选字段
	if input.Slug != nil {
		createInput.Slug = *input.Slug
	}

	if input.Excerpt != nil {
		createInput.Excerpt = *input.Excerpt
	}

	if input.CoverImageURL != nil {
		createInput.CoverImageURL = *input.CoverImageURL
	}

	if input.AccessLevel != nil {
		var accessLevel string
		switch *input.AccessLevel {
		case AccessLevelPublic:
			accessLevel = "PUBLIC"
		case AccessLevelPrivate:
			accessLevel = "PRIVATE"
		case AccessLevelRestricted:
			accessLevel = "RESTRICTED"
		}
		createInput.AccessLevel = accessLevel
	}

	if input.Status != nil {
		var status string
		switch *input.Status {
		case PostStatusDraft:
			status = "DRAFT"
		case PostStatusPublished:
			status = "PUBLISHED"
		case PostStatusArchived:
			status = "ARCHIVED"
		}
		createInput.Status = status
	}

	if input.PublishAt != nil {
		createInput.PublishAt = input.PublishAt
	}

	// 处理标签和分类
	if len(input.Tags) > 0 {
		createInput.Tags = input.Tags
	}

	if len(input.Categories) > 0 {
		createInput.Categories = input.Categories
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	post, err := blogService.CreatePostFromInput(createInput, user.ID)
	if err != nil {
		// 添加详细错误日志
		middleware.GetLogger().Errorw("CreatePost 失败", 
			"error", err, 
			"userID", user.ID, 
			"title", input.Title,
			"contentLength", len(input.Content))
		return nil, fmt.Errorf("创建文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(post, user), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input UpdatePostInput) (*BlogPost, error) {
	// 解析文章ID
	postID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换输入参数
	updateInput := &models.UpdateBlogPostInput{}

	// 处理可选字段
	if input.Title != nil {
		updateInput.Title = input.Title
	}

	if input.Content != nil {
		updateInput.Content = input.Content
	}

	if input.Slug != nil {
		updateInput.Slug = input.Slug
	}

	if input.Excerpt != nil {
		updateInput.Excerpt = input.Excerpt
	}

	if input.CoverImageURL != nil {
		updateInput.CoverImageURL = input.CoverImageURL
	}

	if input.AccessLevel != nil {
		var accessLevel string
		switch *input.AccessLevel {
		case AccessLevelPublic:
			accessLevel = "PUBLIC"
		case AccessLevelPrivate:
			accessLevel = "PRIVATE"
		case AccessLevelRestricted:
			accessLevel = "RESTRICTED"
		}
		updateInput.AccessLevel = &accessLevel
	}

	if input.Status != nil {
		var status string
		switch *input.Status {
		case PostStatusDraft:
			status = "DRAFT"
		case PostStatusPublished:
			status = "PUBLISHED"
		case PostStatusArchived:
			status = "ARCHIVED"
		}
		updateInput.Status = &status
	}

	if input.ChangeLog != nil {
		updateInput.ChangeLog = *input.ChangeLog
	}

	// 处理标签和分类
	if len(input.Tags) > 0 {
		updateInput.Tags = input.Tags
	}

	if len(input.Categories) > 0 {
		updateInput.Categories = input.Categories
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	post, err := blogService.UpdatePostFromInput(uint(postID), updateInput, user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("更新文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(post, user), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (*GeneralResponse, error) {
	// 解析文章ID
	postID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	err = blogService.DeletePost(uint(postID), user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("删除文章失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("文章删除成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// PublishPost is the resolver for the publishPost field.
func (r *mutationResolver) PublishPost(ctx context.Context, id string) (*BlogPost, error) {
	// 解析文章ID
	postID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	post, err := blogService.PublishPost(uint(postID), user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("发布文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(post, user), nil
}

// ArchivePost is the resolver for the archivePost field.
func (r *mutationResolver) ArchivePost(ctx context.Context, id string) (*BlogPost, error) {
	// 解析文章ID
	postID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	post, err := blogService.ArchivePost(uint(postID), user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("归档文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(post, user), nil
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, id string) (*BlogPost, error) {
	// 解析文章ID
	postID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	post, err := blogService.LikePost(uint(postID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("点赞文章失败: %w", err)
	}

	// 设置点赞状态
	graphqlPost := convertToGraphQLBlogPostWithUser(post, user)
	graphqlPost.IsLiked = true

	return graphqlPost, nil
}

// UnlikePost is the resolver for the unlikePost field.
func (r *mutationResolver) UnlikePost(ctx context.Context, id string) (*BlogPost, error) {
	// 解析文章ID
	postID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	post, err := blogService.UnlikePost(uint(postID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("取消点赞失败: %w", err)
	}

	// 设置点赞状态
	graphqlPost := convertToGraphQLBlogPostWithUser(post, user)
	graphqlPost.IsLiked = false

	return graphqlPost, nil
}

// UploadImage is the resolver for the uploadImage field.
func (r *mutationResolver) UploadImage(ctx context.Context, file graphql.Upload) (*ImageUploadResponse, error) {
	// 简化实现：图片上传功能
	// 实际项目中需要：
	// 1. 验证用户权限
	// 2. 验证文件类型和大小
	// 3. 生成唯一文件名
	// 4. 保存到本地或云存储
	// 5. 返回访问URL

	// 获取当前用户（可选）
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 验证文件是否存在
	if file.File == nil {
		return nil, fmt.Errorf("文件不能为空")
	}

	// 简化实现：不实际处理文件上传
	// 实际项目中应该：
	// 1. 读取文件内容
	// 2. 验证文件类型（image/jpeg, image/png等）
	// 3. 检查文件大小限制
	// 4. 生成唯一文件名
	// 5. 保存文件
	// 6. 返回文件访问URL

	// 生成模拟的URL
	mockURL := fmt.Sprintf("/uploads/images/%d_%s", user.ID, file.Filename)

	return &ImageUploadResponse{
		ImageURL: mockURL,
		Filename: file.Filename,
		Size:     1024, // 模拟文件大小
	}, nil
}

// AdminCreateUser is the resolver for the adminCreateUser field.
func (r *mutationResolver) AdminCreateUser(ctx context.Context, input AdminCreateUserInput) (*User, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 检查用户名是否已存在
	var existingUser models.User
	if err := r.DB.Where("username = ?", input.Username).First(&existingUser).Error; err == nil {
		return nil, ErrUserExists
	}

	// 检查邮箱是否已存在
	if err := r.DB.Where("email = ?", input.Email).First(&existingUser).Error; err == nil {
		return nil, GraphQLError{Message: "邮箱已被使用", Code: "EMAIL_EXISTS"}
	}

	// 创建新用户
	role := "user" // 默认角色
	if input.Role != nil {
		role = string(*input.Role)
	}

	user := models.User{
		Username:   input.Username,
		Email:      input.Email,
		Password:   input.Password, // 应该在模型中自动哈希
		Role:       role,
		IsVerified: *input.IsVerified,
		IsActive:   true,
	}

	if err := r.DB.Create(&user).Error; err != nil {
		return nil, fmt.Errorf("创建用户失败: %w", err)
	}

	return convertToGraphQLUser(&user), nil
}

// AdminUpdateUser is the resolver for the adminUpdateUser field.
func (r *mutationResolver) AdminUpdateUser(ctx context.Context, id string, username *string, email *string, role *UserRole, isVerified *bool, isActive *bool) (*User, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 解析用户ID
	userID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 查找用户
	var user models.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 更新字段
	if username != nil {
		// 检查用户名是否已被其他用户使用
		var existingUser models.User
		if err := r.DB.Where("username = ? AND id != ?", *username, userID).First(&existingUser).Error; err == nil {
			return nil, GraphQLError{Message: "用户名已被使用", Code: "USERNAME_EXISTS"}
		}
		user.Username = *username
	}

	if email != nil {
		// 检查邮箱是否已被其他用户使用
		var existingUser models.User
		if err := r.DB.Where("email = ? AND id != ?", *email, userID).First(&existingUser).Error; err == nil {
			return nil, GraphQLError{Message: "邮箱已被使用", Code: "EMAIL_EXISTS"}
		}
		user.Email = *email
	}

	if role != nil {
		user.Role = string(*role)
	}

	if isVerified != nil {
		user.IsVerified = *isVerified
	}

	if isActive != nil {
		user.IsActive = *isActive
	}

	// 保存更新
	if err := r.DB.Save(&user).Error; err != nil {
		return nil, fmt.Errorf("更新用户失败: %w", err)
	}

	return convertToGraphQLUser(&user), nil
}

// AdminDeleteUser is the resolver for the adminDeleteUser field.
func (r *mutationResolver) AdminDeleteUser(ctx context.Context, id string) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 解析用户ID
	userID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 查找用户
	var user models.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 不能删除管理员账户（安全限制）
	if user.Role == "admin" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("不能删除管理员账户"),
			Code:    strPtr("CANNOT_DELETE_ADMIN"),
		}, nil
	}

	// 开始事务，同时删除用户相关数据
	tx := r.DB.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// 删除用户的文章（软删除）
	if err := tx.Where("author_id = ?", userID).Delete(&models.BlogPost{}).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("删除用户文章失败: %w", err)
	}

	// 删除用户的评论
	if err := tx.Where("user_id = ?", userID).Delete(&models.BlogPostComment{}).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("删除用户评论失败: %w", err)
	}

	// 删除用户账户
	if err := tx.Delete(&user).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("删除用户失败: %w", err)
	}

	if err := tx.Commit().Error; err != nil {
		return nil, fmt.Errorf("提交删除用户事务失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("用户删除成功"),
		Code:    strPtr("DELETE_SUCCESS"),
	}, nil
}

// CreateInviteCode is the resolver for the createInviteCode field.
func (r *mutationResolver) CreateInviteCode(ctx context.Context, input CreateInviteCodeInput) (*InviteCode, error) {
	// 验证管理员权限
	currentUser, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 生成唯一的邀请码
	code := generateInviteCode()
	
	// 验证邀请码唯一性
	var existingCode models.InviteCode
	if err := r.DB.Where("code = ?", code).First(&existingCode).Error; err == nil {
		// 如果存在重复，重新生成
		code = generateInviteCode()
	}

	// 设置默认值
	maxUses := 1
	if input.MaxUses != nil {
		maxUses = *input.MaxUses
	}

	// 创建邀请码
	inviteCode := models.InviteCode{
		Code:        code,
		CreatedByID: currentUser.ID,
		MaxUses:     maxUses,
		CurrentUses: 0,
		IsActive:    true,
	}

	// 处理可选字段
	if input.Description != nil {
		inviteCode.Description = *input.Description
	}

	if !input.ExpiresAt.IsZero() {
		inviteCode.ExpiresAt = input.ExpiresAt
	}

	// 保存到数据库
	if err := r.DB.Create(&inviteCode).Error; err != nil {
		return nil, fmt.Errorf("创建邀请码失败: %w", err)
	}

	// 预加载关联数据
	if err := r.DB.Preload("CreatedBy").First(&inviteCode, inviteCode.ID).Error; err != nil {
		return nil, fmt.Errorf("获取邀请码详情失败: %w", err)
	}

	// 转换为GraphQL类型
	var description *string
	if inviteCode.Description != "" {
		description = &inviteCode.Description
	}

	return &InviteCode{
		ID:          strconv.FormatUint(uint64(inviteCode.ID), 10),
		Code:        inviteCode.Code,
		CreatedBy:   convertToGraphQLUser(&inviteCode.CreatedBy),
		UsedBy:      nil, // 新创建的邀请码未被使用
		UsedAt:      nil,
		ExpiresAt:   inviteCode.ExpiresAt,
		MaxUses:     inviteCode.MaxUses,
		CurrentUses: inviteCode.CurrentUses,
		IsActive:    inviteCode.IsActive,
		Description: description,
		CreatedAt:   inviteCode.CreatedAt,
	}, nil
}

// DeactivateInviteCode is the resolver for the deactivateInviteCode field.
func (r *mutationResolver) DeactivateInviteCode(ctx context.Context, id string) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 解析邀请码ID
	inviteCodeID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 查找邀请码
	var inviteCode models.InviteCode
	if err := r.DB.First(&inviteCode, inviteCodeID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return &GeneralResponse{
				Success: false,
				Message: strPtr("邀请码不存在"),
				Code:    strPtr("INVITE_CODE_NOT_FOUND"),
			}, nil
		}
		return nil, fmt.Errorf("查询邀请码失败: %w", err)
	}

	// 检查邀请码是否已经被停用
	if !inviteCode.IsActive {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("邀请码已经被停用"),
			Code:    strPtr("INVITE_CODE_ALREADY_INACTIVE"),
		}, nil
	}

	// 停用邀请码
	if err := r.DB.Model(&inviteCode).Update("is_active", false).Error; err != nil {
		return nil, fmt.Errorf("停用邀请码失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("邀请码已成功停用"),
		Code:    strPtr("DEACTIVATE_SUCCESS"),
	}, nil
}

// ClearCache is the resolver for the clearCache field.
func (r *mutationResolver) ClearCache(ctx context.Context) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 在这个简化版本中，我们主要清理搜索服务的缓存
	// 实际项目中，这里可能需要清理Redis缓存、内存缓存等
	if r.Resolver.SearchService != nil {
		// 如果搜索服务有清理缓存的方法，可以在这里调用
		// r.Resolver.SearchService.ClearCache()
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("缓存清理成功"),
		Code:    strPtr("CACHE_CLEARED"),
	}, nil
}

// RebuildSearchIndex is the resolver for the rebuildSearchIndex field.
func (r *mutationResolver) RebuildSearchIndex(ctx context.Context) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 重建搜索索引（简化版本）
	// 实际项目中，这里可能需要：
	// 1. 清除现有索引
	// 2. 重新索引所有文章
	// 3. 更新搜索统计
	if r.Resolver.SearchService != nil {
		// 如果搜索服务有重建索引的方法，可以在这里调用
		// err := r.Resolver.SearchService.RebuildIndex()
		// if err != nil {
		//     return &GeneralResponse{
		//         Success: false,
		//         Message: strPtr("重建搜索索引失败"),
		//         Code:    strPtr("REBUILD_INDEX_FAILED"),
		//     }, nil
		// }
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("搜索索引重建成功"),
		Code:    strPtr("INDEX_REBUILT"),
	}, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input CreateCommentInput) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换博客文章ID
	blogPostID, err := strconv.ParseUint(input.BlogPostID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 转换父评论ID（如果提供）
	var parentID *uint
	if input.ParentID != nil {
		pid, err := strconv.ParseUint(*input.ParentID, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("无效的父评论ID: %w", err)
		}
		parentIDUint := uint(pid)
		parentID = &parentIDUint
	}

	// 准备服务层输入
	serviceInput := &services.CreateCommentInput{
		Content:    input.Content,
		BlogPostID: uint(blogPostID),
		ParentID:   parentID,
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 创建评论
	comment, err := commentService.CreateComment(serviceInput, user.ID)
	if err != nil {
		return nil, fmt.Errorf("创建评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, input UpdateCommentInput) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 更新评论
	comment, err := commentService.UpdateComment(uint(commentID), input.Content, user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("更新评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (*GeneralResponse, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 删除评论
	err = commentService.DeleteComment(uint(commentID), user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("删除评论失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("评论删除成功"),
		Code:    strPtr("DELETE_SUCCESS"),
	}, nil
}

// LikeComment is the resolver for the likeComment field.
func (r *mutationResolver) LikeComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 点赞评论
	comment, err := commentService.LikeComment(uint(commentID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("点赞评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// UnlikeComment is the resolver for the unlikeComment field.
func (r *mutationResolver) UnlikeComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 取消点赞评论
	comment, err := commentService.UnlikeComment(uint(commentID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("取消点赞评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// ReportComment is the resolver for the reportComment field.
func (r *mutationResolver) ReportComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 举报评论
	comment, err := commentService.ReportComment(uint(commentID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("举报评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	// 获取当前用户信息
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未找到用户信息: %w", err)
	}

	// 确保用户对象不为nil
	if user == nil {
		return nil, fmt.Errorf("用户信息为空")
	}

	return convertToGraphQLUser(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	// 解析用户ID
	userID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的用户ID: %w", err)
	}

	// 从数据库获取用户
	var user models.User
	if err := r.Resolver.DB.First(&user, userID).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("用户不存在")
		}
		return nil, fmt.Errorf("数据库错误: %w", err)
	}

	return convertToGraphQLUser(&user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int, search *string, role *UserRole, isVerified *bool) ([]*User, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.User{})

	// 应用搜索条件
	if search != nil && *search != "" {
		dbQuery = dbQuery.Where("username LIKE ? OR email LIKE ?", "%"+*search+"%", "%"+*search+"%")
	}

	// 应用角色过滤
	if role != nil {
		var roleStr string
		switch *role {
		case UserRoleAdmin:
			roleStr = "admin"
		case UserRoleUser:
			roleStr = "user"
		}
		dbQuery = dbQuery.Where("role = ?", roleStr)
	}

	// 应用验证状态过滤
	if isVerified != nil {
		dbQuery = dbQuery.Where("is_verified = ?", *isVerified)
	}

	// 获取结果
	var users []models.User
	err := dbQuery.Offset(*offset).Limit(*limit).Find(&users).Error
	if err != nil {
		return nil, fmt.Errorf("获取用户列表失败: %w", err)
	}

	// 转换结果
	result := make([]*User, len(users))
	for i, user := range users {
		result[i] = convertToGraphQLUser(&user)
	}

	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id *string, slug *string) (*BlogPost, error) {
	// 必须提供id或slug中的一个
	if id == nil && slug == nil {
		return nil, fmt.Errorf("必须提供id或slug")
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPost{}).
		Preload("Author").
		Preload("Stats")

	// 根据ID或slug查询
	if id != nil {
		postID, err := strconv.ParseUint(*id, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("无效的文章ID: %w", err)
		}
		dbQuery = dbQuery.Where("id = ?", postID)
	} else if slug != nil {
		dbQuery = dbQuery.Where("slug = ?", *slug)
	}

	// 权限过滤
	if currentUser == nil || currentUser.Role != "admin" {
		dbQuery = dbQuery.Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'")
	} else if currentUser.Role != "admin" {
		dbQuery = dbQuery.Where("(status = 'PUBLISHED' AND access_level = 'PUBLIC') OR author_id = ?", currentUser.ID)
	}

	// 获取结果
	var post models.BlogPost
	err := dbQuery.First(&post).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("文章不存在")
		}
		return nil, fmt.Errorf("数据库错误: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(&post, currentUser), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int, offset *int, filter *PostFilterInput, sort *PostSortInput) ([]*BlogPost, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPost{}).
		Preload("Author").
		Preload("Stats")

	// 权限过滤
	if currentUser == nil || currentUser.Role != "admin" {
		dbQuery = dbQuery.Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'")
	} else if currentUser.Role != "admin" {
		dbQuery = dbQuery.Where("(status = 'PUBLISHED' AND access_level = 'PUBLIC') OR author_id = ?", currentUser.ID)
	}

	// 应用过滤条件
	if filter != nil {
		// 作者过滤
		if filter.AuthorID != nil {
			authorID, err := strconv.ParseUint(*filter.AuthorID, 10, 64)
			if err == nil {
				dbQuery = dbQuery.Where("author_id = ?", authorID)
			}
		}

		// 状态过滤
		if filter.Status != nil {
			var statusStr string
			switch *filter.Status {
			case PostStatusDraft:
				statusStr = "DRAFT"
			case PostStatusPublished:
				statusStr = "PUBLISHED"
			case PostStatusArchived:
				statusStr = "ARCHIVED"
			}
			dbQuery = dbQuery.Where("status = ?", statusStr)
		}

		// 访问级别过滤
		if filter.AccessLevel != nil {
			var accessLevelStr string
			switch *filter.AccessLevel {
			case AccessLevelPublic:
				accessLevelStr = "PUBLIC"
			case AccessLevelPrivate:
				accessLevelStr = "PRIVATE"
			case AccessLevelRestricted:
				accessLevelStr = "RESTRICTED"
			}
			dbQuery = dbQuery.Where("access_level = ?", accessLevelStr)
		}

		// 标签过滤
		if len(filter.Tags) > 0 {
			for _, tag := range filter.Tags {
				dbQuery = dbQuery.Where("tags LIKE ?", "%"+tag+"%")
			}
		}

		// 分类过滤
		if len(filter.Categories) > 0 {
			for _, category := range filter.Categories {
				dbQuery = dbQuery.Where("categories LIKE ?", "%"+category+"%")
			}
		}

		// 搜索过滤
		if filter.Search != nil && *filter.Search != "" {
			searchTerm := "%" + *filter.Search + "%"
			dbQuery = dbQuery.Where("(title LIKE ? OR content LIKE ? OR tags LIKE ? OR categories LIKE ?)", searchTerm, searchTerm, searchTerm, searchTerm)
		}

		// 日期范围过滤
		if filter.DateFrom != nil {
			dbQuery = dbQuery.Where("created_at >= ?", *filter.DateFrom)
		}
		if filter.DateTo != nil {
			dbQuery = dbQuery.Where("created_at <= ?", *filter.DateTo)
		}
	}

	// 应用排序
	orderClause := "created_at DESC"
	if sort != nil && sort.Field != nil && sort.Order != nil {
		// 验证字段名以防止SQL注入
		validFields := map[string]bool{
			"created_at":   true,
			"updated_at":   true,
			"published_at": true,
			"view_count":   true,
			"like_count":   true,
		}

		if validFields[*sort.Field] {
			orderClause = *sort.Field + " " + *sort.Order
		}
	}
	dbQuery = dbQuery.Order(orderClause)

	// 获取结果
	var posts []models.BlogPost
	err := dbQuery.Offset(*offset).Limit(*limit).Find(&posts).Error
	if err != nil {
		return nil, fmt.Errorf("获取文章列表失败: %w", err)
	}

	// 确保所有文章都有统计记录
	for i := range posts {
		if posts[i].Stats == nil {
			// 尝试创建统计记录
			if statsErr := ensurePostStats(r.Resolver.DB, posts[i].ID); statsErr == nil {
				// 重新加载stats
				r.Resolver.DB.Preload("Stats").First(&posts[i], posts[i].ID)
			}
		}
	}

	// 转换结果
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPostWithUser(&post, currentUser)
	}

	return result, nil
}

// PostVersions is the resolver for the postVersions field.
func (r *queryResolver) PostVersions(ctx context.Context, postID string) ([]*BlogPostVersion, error) {
	// 解析文章ID
	id, err := strconv.ParseUint(postID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户信息
	currentUser, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("需要登录才能查看文章版本: %w", err)
	}

	// 检查用户是否有权限查看文章版本
	var post models.BlogPost
	if err := r.Resolver.DB.First(&post, id).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("文章不存在")
		}
		return nil, fmt.Errorf("数据库错误: %w", err)
	}

	// 只有文章作者或管理员可以查看版本
	if post.AuthorID != currentUser.ID && currentUser.Role != "admin" {
		return nil, fmt.Errorf("权限不足")
	}

	// 获取版本历史
	var versions []models.BlogPostVersion
	err = r.Resolver.DB.Where("blog_post_id = ?", id).
		Preload("CreatedBy").
		Order("version_num DESC").
		Find(&versions).Error

	if err != nil {
		return nil, fmt.Errorf("获取文章版本失败: %w", err)
	}

	// 转换结果
	result := make([]*BlogPostVersion, len(versions))
	for i, version := range versions {
		result[i] = &BlogPostVersion{
			ID:         strconv.FormatUint(uint64(version.ID), 10),
			VersionNum: version.VersionNum,
			Title:      version.Title,
			Content:    version.Content,
			ChangeLog:  &version.ChangeLog,
			CreatedAt:  version.CreatedAt,
			CreatedBy:  convertToGraphQLUser(&version.CreatedBy),
		}
	}

	return result, nil
}

// SearchPosts is the resolver for the searchPosts field.
func (r *queryResolver) SearchPosts(ctx context.Context, query string, limit *int, offset *int) (*SearchResult, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 获取当前用户信息（如果有的话）
	var userID *uint
	var userRole string = "user"

	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	result, err := searchService.AdvancedSearchPosts(query, *limit, *offset, userID, userRole)
	if err != nil {
		return nil, fmt.Errorf("搜索失败: %w", err)
	}

	// 转换结果
	posts := make([]*BlogPost, len(result.Posts))
	for i, post := range result.Posts {
		posts[i] = convertToGraphQLBlogPostWithUser(post, nil) // TODO: 传递当前用户信息以设置isLiked
	}

	return &SearchResult{
		Posts: posts,
		Total: int(result.Total),
		Took:  result.Took.String(),
	}, nil
}

// EnhancedSearch is the resolver for the enhancedSearch field.
func (r *queryResolver) EnhancedSearch(ctx context.Context, input SearchInput) (*EnhancedSearchResult, error) {
	// 设置默认值
	query := input.Query
	limit := 10
	offset := 0

	if input.Limit != nil {
		limit = *input.Limit
	}

	if input.Offset != nil {
		offset = *input.Offset
	}

	// 获取当前用户信息（如果有的话）
	var userID *uint
	var userRole string = "user"

	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	result, err := searchService.AdvancedSearchPosts(query, limit, offset, userID, userRole)
	if err != nil {
		return nil, fmt.Errorf("增强搜索失败: %w", err)
	}

	// 转换结果
	posts := make([]*BlogPost, len(result.Posts))
	for i, post := range result.Posts {
		posts[i] = convertToGraphQLBlogPostWithUser(post, nil) // TODO: 传递当前用户信息以设置isLiked
	}

	// 获取搜索建议
	suggestions, err := searchService.GetSearchSuggestions(query, 5)
	if err != nil {
		// 不中断搜索，只记录错误
		suggestions = []string{}
	}

	// 获取聚合信息
	tagFacets, _ := searchService.GetTagFacets(query, 10)
	categoryFacets, _ := searchService.GetCategoryFacets(query, 10)
	authorFacets, _ := searchService.GetAuthorFacets(query, 10)

	// 转换聚合信息
	tags := make([]*SearchFacetItem, len(tagFacets))
	for i, facet := range tagFacets {
		tags[i] = &SearchFacetItem{
			Value: facet.Value,
			Count: facet.Count,
		}
	}

	categories := make([]*SearchFacetItem, len(categoryFacets))
	for i, facet := range categoryFacets {
		categories[i] = &SearchFacetItem{
			Value: facet.Value,
			Count: facet.Count,
		}
	}

	authors := make([]*SearchFacetItem, len(authorFacets))
	for i, facet := range authorFacets {
		authors[i] = &SearchFacetItem{
			Value: facet.Value,
			Count: facet.Count,
		}
	}

	return &EnhancedSearchResult{
		Posts:       posts,
		Total:       int(result.Total),
		Took:        result.Took.String(),
		Suggestions: suggestions,
		Facets: &SearchFacets{
			Tags:       tags,
			Categories: categories,
			Authors:    authors,
		},
	}, nil
}

// GetSearchSuggestions is the resolver for the getSearchSuggestions field.
func (r *queryResolver) GetSearchSuggestions(ctx context.Context, query string, limit *int) ([]string, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	suggestions, err := searchService.GetSearchSuggestions(query, *limit)
	if err != nil {
		return nil, fmt.Errorf("获取搜索建议失败: %w", err)
	}

	return suggestions, nil
}

// GetTrendingSearches is the resolver for the getTrendingSearches field.
func (r *queryResolver) GetTrendingSearches(ctx context.Context, limit *int) ([]string, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	trending, err := searchService.GetTrendingSearches(*limit)
	if err != nil {
		return nil, fmt.Errorf("获取热门搜索词失败: %w", err)
	}

	return trending, nil
}

// GetSearchStats is the resolver for the getSearchStats field.
func (r *queryResolver) GetSearchStats(ctx context.Context) (*SearchStats, error) {
	// 获取基本统计信息
	var totalSearches int64
	if err := r.Resolver.DB.Model(&models.BlogPost{}).Count(&totalSearches).Error; err != nil {
		return nil, fmt.Errorf("获取文章总数失败: %w", err)
	}

	// 获取热门查询（简化实现：使用热门标签）
	searchService := r.Resolver.SearchService
	trendingTags, err := searchService.GetTrendingSearches(10)
	if err != nil {
		trendingTags = []string{}
	}

	// 构建热门查询数据
	popularQueries := make([]*PopularQuery, len(trendingTags))
	for i, tag := range trendingTags {
		popularQueries[i] = &PopularQuery{
			Query:        tag,
			Count:        0, // 简化实现，实际应该统计查询次数
			LastSearched: time.Now(),
		}
	}

	// 构建搜索趋势数据（简化实现）
	searchTrends := make([]*SearchTrend, 0)

	return &SearchStats{
		TotalSearches:  int(totalSearches),
		PopularQueries: popularQueries,
		SearchTrends:   searchTrends,
	}, nil
}

// InviteCodes is the resolver for the inviteCodes field.
func (r *queryResolver) InviteCodes(ctx context.Context, limit *int, offset *int, isActive *bool) ([]*InviteCode, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.InviteCode{}).
		Preload("CreatedBy").
		Preload("UsedBy")

	// 应用激活状态过滤
	if isActive != nil {
		dbQuery = dbQuery.Where("is_active = ?", *isActive)
	}

	// 获取结果
	var inviteCodes []models.InviteCode
	err := dbQuery.Offset(*offset).Limit(*limit).Find(&inviteCodes).Error
	if err != nil {
		return nil, fmt.Errorf("获取邀请码列表失败: %w", err)
	}

	// 转换结果
	result := make([]*InviteCode, len(inviteCodes))
	for i, inviteCode := range inviteCodes {
		// 处理可选字段
		var description *string
		if inviteCode.Description != "" {
			description = &inviteCode.Description
		}

		result[i] = &InviteCode{
			ID:          strconv.FormatUint(uint64(inviteCode.ID), 10),
			Code:        inviteCode.Code,
			CreatedBy:   convertToGraphQLUser(&inviteCode.CreatedBy),
			UsedBy:      convertToGraphQLUser(inviteCode.UsedBy),
			UsedAt:      inviteCode.UsedAt,
			ExpiresAt:   inviteCode.ExpiresAt,
			MaxUses:     inviteCode.MaxUses,
			CurrentUses: inviteCode.CurrentUses,
			IsActive:    inviteCode.IsActive,
			Description: description,
			CreatedAt:   inviteCode.CreatedAt,
		}
	}

	return result, nil
}

// ServerDashboard is the resolver for the serverDashboard field.
func (r *queryResolver) ServerDashboard(ctx context.Context) (*ServerDashboard, error) {
	// 获取内存统计信息
	var memStats runtime.MemStats
	runtime.ReadMemStats(&memStats)

	// 格式化内存信息为字符串
	memory := &ServerMemoryStats{
		Alloc:      fmt.Sprintf("%.2f MB", float64(memStats.Alloc)/1024/1024),
		TotalAlloc: fmt.Sprintf("%.2f MB", float64(memStats.TotalAlloc)/1024/1024),
		Sys:        fmt.Sprintf("%.2f MB", float64(memStats.Sys)/1024/1024),
		HeapAlloc:  fmt.Sprintf("%.2f MB", float64(memStats.HeapAlloc)/1024/1024),
		HeapSys:    fmt.Sprintf("%.2f MB", float64(memStats.HeapSys)/1024/1024),
	}

	// 获取主机名
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "unknown"
	}

	// 获取用户数量
	var userCount int64
	if err := r.Resolver.DB.Model(&models.User{}).Count(&userCount).Error; err != nil {
		return nil, fmt.Errorf("获取用户数量失败: %w", err)
	}

	// 获取文章数量
	var postCount int64
	if err := r.Resolver.DB.Model(&models.BlogPost{}).Count(&postCount).Error; err != nil {
		return nil, fmt.Errorf("获取文章数量失败: %w", err)
	}

	// 获取今日注册用户数
	var todayRegistrations int64
	today := time.Now().Truncate(24 * time.Hour)
	if err := r.Resolver.DB.Model(&models.User{}).
		Where("created_at >= ?", today).
		Count(&todayRegistrations).Error; err != nil {
		return nil, fmt.Errorf("获取今日注册用户数失败: %w", err)
	}

	// 获取今日发布文章数
	var todayPosts int64
	if err := r.Resolver.DB.Model(&models.BlogPost{}).
		Where("created_at >= ?", today).
		Count(&todayPosts).Error; err != nil {
		return nil, fmt.Errorf("获取今日发布文章数失败: %w", err)
	}

	// 构建返回结果
	return &ServerDashboard{
		ServerTime:         time.Now(),
		Hostname:           hostname,
		GoVersion:          runtime.Version(),
		CPUCount:           runtime.NumCPU(),
		Goroutines:         runtime.NumGoroutine(),
		Memory:             memory,
		Uptime:             "0 days", // 简化实现，实际应该记录服务启动时间
		UserCount:          int(userCount),
		PostCount:          int(postCount),
		TodayRegistrations: int(todayRegistrations),
		TodayPosts:         int(todayPosts),
	}, nil
}

// GetPopularPosts is the resolver for the getPopularPosts field.
func (r *queryResolver) GetPopularPosts(ctx context.Context, limit *int) ([]*BlogPost, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 限制最大返回数量
	if *limit > 100 {
		*limit = 100
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 查询热门文章，按点赞数和浏览量排序
	var posts []models.BlogPost
	err := r.Resolver.DB.Model(&models.BlogPost{}).
		Preload("Author").
		Preload("Stats").
		Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'").
		Joins("LEFT JOIN blog_post_stats stats ON blog_post.id = stats.blog_post_id"). // 正确关联统计表并使用别名
		Order("stats.like_count DESC, stats.view_count DESC, blog_post.created_at DESC").
		Limit(*limit).
		Find(&posts).Error

	if err != nil {
		return nil, fmt.Errorf("获取热门文章失败: %w", err)
	}

	// 确保所有文章都有统计记录
	for i := range posts {
		if posts[i].Stats == nil {
			// 尝试创建统计记录
			if statsErr := ensurePostStats(r.Resolver.DB, posts[i].ID); statsErr == nil {
				// 重新加载stats
				r.Resolver.DB.Preload("Stats").First(&posts[i], posts[i].ID)
			}
		}
	}

	// 转换结果
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPostWithUser(&post, currentUser)
	}

	return result, nil
}

// GetRecentPosts is the resolver for the getRecentPosts field.
func (r *queryResolver) GetRecentPosts(ctx context.Context, limit *int) ([]*BlogPost, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 限制最大返回数量
	if *limit > 100 {
		*limit = 100
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 查询最新文章，按创建时间排序
	var posts []models.BlogPost
	err := r.Resolver.DB.Model(&models.BlogPost{}).
		Preload("Author").
		Preload("Stats").
		Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'").
		Order("created_at DESC").
		Limit(*limit).
		Find(&posts).Error

	if err != nil {
		return nil, fmt.Errorf("获取最新文章失败: %w", err)
	}

	// 确保所有文章都有统计记录
	for i := range posts {
		if posts[i].Stats == nil {
			// 尝试创建统计记录
			if statsErr := ensurePostStats(r.Resolver.DB, posts[i].ID); statsErr == nil {
				// 重新加载stats
				r.Resolver.DB.Preload("Stats").First(&posts[i], posts[i].ID)
			}
		}
	}

	// 转换结果
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPostWithUser(&post, currentUser)
	}

	return result, nil
}

// GetTrendingTags is the resolver for the getTrendingTags field.
func (r *queryResolver) GetTrendingTags(ctx context.Context, limit *int) ([]string, error) {
	// 设置默认值
	defaultLimit := 20
	if limit == nil {
		limit = &defaultLimit
	}

	// 限制最大返回数量
	if *limit > 100 {
		*limit = 100
	}

	// 使用搜索服务获取热门标签
	searchService := r.Resolver.SearchService
	trendingTags, err := searchService.GetTrendingSearches(*limit)
	if err != nil {
		// 如果搜索服务失败，返回空数组而不是错误
		return []string{}, nil
	}

	return trendingTags, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, blogPostID string, limit *int, offset *int, filter *CommentFilterInput, sort *CommentSortInput) (*CommentResult, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 解析文章ID
	postID, err := strconv.ParseUint(blogPostID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPostComment{}).
		Preload("User").
		Preload("Parent").
		Preload("Replies").
		Where("blog_post_id = ?", postID)

	// 权限过滤 - 只显示已审核的评论，除非是管理员或作者
	if currentUser == nil || (currentUser.Role != "admin" && postID != 0) {
		dbQuery = dbQuery.Where("is_approved = ?", true)
	}

	// 应用过滤条件
	if filter != nil {
		// 用户ID过滤
		if filter.UserID != nil {
			userID, err := strconv.ParseUint(*filter.UserID, 10, 64)
			if err == nil {
				dbQuery = dbQuery.Where("user_id = ?", userID)
			}
		}

		// 审核状态过滤
		if filter.IsApproved != nil {
			dbQuery = dbQuery.Where("is_approved = ?", *filter.IsApproved)
		}
	}

	// 应用排序
	orderClause := "created_at DESC"
	if sort != nil && sort.Field != nil && sort.Order != nil {
		// 验证字段名以防止SQL注入
		validFields := map[string]bool{
			"created_at": true,
			"like_count": true,
		}

		if validFields[*sort.Field] {
			orderClause = *sort.Field + " " + *sort.Order
		}
	}
	dbQuery = dbQuery.Order(orderClause)

	// 获取总数
	var total int64
	countQuery := dbQuery
	if err := countQuery.Count(&total).Error; err != nil {
		return nil, fmt.Errorf("获取评论总数失败: %w", err)
	}

	// 获取结果
	var comments []models.BlogPostComment
	err = dbQuery.Offset(*offset).Limit(*limit).Find(&comments).Error
	if err != nil {
		return nil, fmt.Errorf("获取评论列表失败: %w", err)
	}

	// 转换结果
	result := make([]*BlogPostComment, len(comments))
	for i, comment := range comments {
		result[i] = convertToGraphQLComment(&comment)
	}

	return &CommentResult{
		Comments: result,
		Total:    int(total),
	}, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 解析评论ID
	commentID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPostComment{}).
		Preload("User").
		Preload("Parent").
		Preload("Replies").
		Preload("BlogPost").
		Where("id = ?", commentID)

	// 权限过滤 - 只显示已审核的评论，除非是管理员或作者
	if currentUser == nil || currentUser.Role != "admin" {
		dbQuery = dbQuery.Where("is_approved = ?", true)
	}

	// 获取结果
	var comment models.BlogPostComment
	err = dbQuery.First(&comment).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("评论不存在")
		}
		return nil, fmt.Errorf("数据库错误: %w", err)
	}

	return convertToGraphQLComment(&comment), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
