package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"errors"
	"fmt"
	"os"
	"repair-platform/middleware"
	"repair-platform/models"
	"repair-platform/services"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// Author is the resolver for the author field.
func (r *blogPostResolver) Author(ctx context.Context, obj *BlogPost) (*User, error) {
	if obj.Author != nil {
		return obj.Author, nil
	}

	// Parse AuthorID
	authorID, err := strconv.ParseUint(obj.AuthorID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid author id: %v", err)
	}

	// Use DataLoader
	loader := GetDataLoaderFromContext(ctx)
	if loader == nil {
		// Fallback to direct DB query
		var user models.User
		if err := r.Resolver.DB.First(&user, uint(authorID)).Error; err != nil {
			// 返回幽灵作者
			return &User{
				ID:       "0",
				Username: "Ghost",
				Email:    "ghost@c404.cc",
				Role:     UserRoleUser,
			}, nil
		}
		return convertToGraphQLUser(&user), nil
	}

	user, err := loader.LoadAuthor(ctx, uint(authorID))
	if err != nil || user == nil {
		// 返回幽灵作者以满足 GraphQL 非空约束
		return &User{
			ID:       "0",
			Username: "Ghost",
			Email:    "ghost@c404.cc",
			Role:     UserRoleUser,
		}, nil
	}
	gUser := convertToGraphQLUser(user)
	if gUser.CreatedAt.IsZero() {
		gUser.CreatedAt = time.Now()
	}
	return gUser, nil
}

// Versions is the resolver for the versions field.
func (r *blogPostResolver) Versions(ctx context.Context, obj *BlogPost) ([]*BlogPostVersion, error) {
	// 解析文章ID
	postID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return []*BlogPostVersion{}, nil
	}

	// 获取版本历史
	var versions []models.BlogPostVersion
	err = r.Resolver.DB.Where("blog_post_id = ?", uint(postID)).
		Preload("CreatedBy").
		Order("version_num DESC").
		Find(&versions).Error

	if err != nil {
		return []*BlogPostVersion{}, nil
	}

	// 转换结果
	result := make([]*BlogPostVersion, len(versions))
	for i, version := range versions {
		result[i] = &BlogPostVersion{
			ID:         strconv.FormatUint(uint64(version.ID), 10),
			VersionNum: version.VersionNum,
			Title:      version.Title,
			Content:    version.Content,
			ChangeLog:  strPtr(version.ChangeLog),
			CreatedAt:  version.CreatedAt,
		}
		if version.CreatedBy.ID != 0 {
			result[i].CreatedBy = convertToGraphQLUser(&version.CreatedBy)
		}
	}

	return result, nil
}

// Stats is the resolver for the stats field.
func (r *blogPostResolver) Stats(ctx context.Context, obj *BlogPost) (*BlogPostStats, error) {
	fmt.Printf("[DEBUG] Stats resolver called for Post ID: %s\n", obj.ID)
	if obj.Stats != nil {
		fmt.Printf("[DEBUG] Stats already in obj for Post %s, UpdatedAt: %v\n", obj.ID, obj.Stats.UpdatedAt)
		return obj.Stats, nil
	}

	// Parse PostID
	postID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %v", err)
	}

	loader := GetDataLoaderFromContext(ctx)
	if loader == nil {
		// Fallback
		var stats models.BlogPostStats
		err := r.Resolver.DB.Where("blog_post_id = ?", uint(postID)).First(&stats).Error
		if err != nil {
			// Return default stats if not found
			return &BlogPostStats{
				ID:        strconv.FormatUint(uint64(postID), 10) + "_stats",
				ViewCount: 0,
				LikeCount: 0,
			}, nil
		}
		// 确保 UpdatedAt 不为零值
		updatedAt := stats.UpdatedAt
		if updatedAt.IsZero() {
			updatedAt = stats.CreatedAt
			if updatedAt.IsZero() {
				updatedAt = time.Now()
			}
		}

		return &BlogPostStats{
			ID:           strconv.FormatUint(uint64(stats.ID), 10),
			ViewCount:    stats.ViewCount,
			LikeCount:    stats.LikeCount,
			ShareCount:   stats.ShareCount,
			CommentCount: stats.CommentCount,
			LastViewedAt: stats.LastViewedAt,
			UpdatedAt:    updatedAt,
		}, nil
	}

	stats, err := loader.LoadStats(ctx, uint(postID))
	if err != nil || stats == nil {
		// 容灾处理：返回默认统计
		return &BlogPostStats{
			ID:        strconv.FormatUint(uint64(postID), 10) + "_stats",
			ViewCount: 0,
			LikeCount: 0,
			UpdatedAt: time.Now(),
		}, nil
	}

	// 确保 UpdatedAt 不为零值
	updatedAt := stats.UpdatedAt
	if updatedAt.IsZero() {
		updatedAt = stats.CreatedAt
		if updatedAt.IsZero() {
			updatedAt = time.Now()
		}
	}

	return &BlogPostStats{
		ID:           strconv.FormatUint(uint64(stats.ID), 10),
		ViewCount:    stats.ViewCount,
		LikeCount:    stats.LikeCount,
		ShareCount:   stats.ShareCount,
		CommentCount: stats.CommentCount,
		LastViewedAt: stats.LastViewedAt,
		UpdatedAt:    updatedAt,
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*AuthPayload, error) {
	// 转换输入参数
	registerInput := &models.RegisterInput{
		Username:   input.Username,
		Email:      input.Email,
		Password:   input.Password,
		InviteCode: "",
	}

	if input.InviteCode != nil {
		registerInput.InviteCode = *input.InviteCode
	}

	// 调用认证服务
	authService := services.NewAuthService(r.Resolver.DB)
	user, token, err := authService.Register(registerInput)
	if err != nil {
		return nil, fmt.Errorf("注册失败: %w", err)
	}

	// 生成刷新令牌
	refreshToken, err := generateSecureRefreshToken()
	if err != nil {
		return nil, fmt.Errorf("生成刷新令牌失败: %w", err)
	}
	expiresAt := time.Now().Add(24 * time.Hour) // 默认24小时过期

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    expiresAt,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	// 转换输入参数
	loginInput := &models.LoginInput{
		Identifier: input.Identifier,
		Password:   input.Password,
		Remember:   false,
	}

	if input.Remember != nil {
		loginInput.Remember = *input.Remember
	}

	// 调用认证服务
	authService := services.NewAuthService(r.Resolver.DB)
	user, token, refreshToken, err := authService.LoginUser(loginInput)
	if err != nil {
		return nil, fmt.Errorf("登录失败: %w", err)
	}

	expiresAt := time.Now().Add(24 * time.Hour) // 默认24小时过期
	if loginInput.Remember {
		expiresAt = time.Now().Add(7 * 24 * time.Hour) // 记住我时7天过期
	}

	return &AuthPayload{
		Token:        token,
		RefreshToken: refreshToken,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    expiresAt,
	}, nil
}

// EmailLogin is the resolver for the emailLogin field.
func (r *mutationResolver) EmailLogin(ctx context.Context, input EmailLoginInput) (*GeneralResponse, error) {
	authService := services.NewAuthService(r.Resolver.DB)
	if err := authService.EmailLogin(input.Email); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(err.Error()),
			Code:    strPtr("EMAIL_SEND_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("验证码已发送到您的邮箱"),
		Code:    strPtr("VERIFICATION_CODE_SENT"),
	}, nil
}

// VerifyEmailAndLogin is the resolver for the verifyEmailAndLogin field.
func (r *mutationResolver) VerifyEmailAndLogin(ctx context.Context, input VerifyEmailInput) (*AuthPayload, error) {
	authService := services.NewAuthService(r.Resolver.DB)
	user, token, refresh, err := authService.VerifyEmailAndLogin(&models.VerifyEmailInput{
		Email: input.Email,
		Code:  input.Code,
		Type:  string(input.Type),
	})
	if err != nil {
		return nil, fmt.Errorf("验证失败: %w", err)
	}

	expiresAt := time.Now().Add(24 * time.Hour)
	return &AuthPayload{
		Token:        token,
		RefreshToken: refresh,
		User:         convertToGraphQLUser(user),
		ExpiresAt:    expiresAt,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken *string) (*GeneralResponse, error) {
	logger := middleware.GetLogger()

	// 1. 获取当前JWT token（从请求头）
	if ginCtx, ok := ctx.(*gin.Context); ok {
		authHeader := ginCtx.GetHeader("Authorization")
		if authHeader != "" && strings.HasPrefix(authHeader, "Bearer ") {
			tokenString := strings.TrimPrefix(authHeader, "Bearer ")

			// 将JWT token添加到黑名单
			blacklist := models.GetTokenBlacklist()
			if err := blacklist.AddToBlacklist(tokenString, "logout"); err != nil {
				logger.Warnw("Failed to blacklist JWT token", "error", err)
			} else {
				logger.Infow("JWT token blacklisted", "token_prefix", tokenString[:min(10, len(tokenString))])
			}
		}
	}

	// 2. 如果提供了 refresh token，撤销它
	if refreshToken != nil && *refreshToken != "" {
		rt, err := models.VerifyRefreshToken(*refreshToken, r.Resolver.DB)
		if err != nil {
			// refresh token 无效或已过期，记录但不影响登出
			logger.Warnw("Invalid refresh token during logout", "error", err)
		} else {
			// 撤销 refresh token
			if err := rt.Revoke(r.Resolver.DB); err != nil {
				logger.Warnw("Failed to revoke refresh token", "error", err)
			} else {
				logger.Infow("Refresh token revoked", "user_id", rt.UserID)
			}
		}
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("成功退出登录"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*AuthPayload, error) {
	logger := middleware.GetLogger()

	// 1. 验证 refresh token
	rt, err := models.VerifyRefreshToken(refreshToken, r.Resolver.DB)
	if err != nil {
		logger.Errorw("Refresh token validation failed", "error", err)
		return nil, fmt.Errorf("无效或过期的refresh token: %w", err)
	}

	// 2. 获取关联的用户
	var user models.User
	if err := r.Resolver.DB.First(&user, rt.UserID).Error; err != nil {
		logger.Errorw("User not found for refresh token", "user_id", rt.UserID, "error", err)
		return nil, fmt.Errorf("用户不存在")
	}

	// 3. 检查用户状态
	if !user.IsActive {
		return nil, fmt.Errorf("用户账户已被禁用")
	}

	// 4. 生成新的 JWT access token
	token, err := models.GenerateJWT(user.ID, user.Username, user.Role, false)
	if err != nil {
		logger.Errorw("Failed to generate new JWT", "error", err)
		return nil, fmt.Errorf("生成token失败")
	}

	// 5. 生成新的 refresh token（旋转策略）
	newRefreshToken, _, err := models.GenerateRefreshToken(user.ID, models.DefaultRefreshTokenConfig, r.Resolver.DB)
	if err != nil {
		logger.Errorw("Failed to generate new refresh token", "error", err)
		// 即使新refresh token生成失败，仍然返回access token
		// 使用旧的refresh token
		newRefreshToken = refreshToken
	} else {
		// 6. 撤销旧的 refresh token（旋转策略）
		if err := rt.Revoke(r.Resolver.DB); err != nil {
			logger.Warnw("Failed to revoke old refresh token", "error", err)
			// 不影响主流程，只记录警告
		}
	}

	expiresAt := time.Now().Add(24 * time.Hour)
	logger.Infow("Token refreshed successfully", "user_id", user.ID)

	return &AuthPayload{
		Token:        token,
		RefreshToken: newRefreshToken,
		User:         convertToGraphQLUser(&user),
		ExpiresAt:    expiresAt,
	}, nil
}

// SendVerificationCode is the resolver for the sendVerificationCode field.
func (r *mutationResolver) SendVerificationCode(ctx context.Context, email string, typeArg VerificationType) (*GeneralResponse, error) {
	// 验证邮箱格式
	if email == "" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("邮箱地址不能为空"),
			Code:    strPtr("EMAIL_REQUIRED"),
		}, nil
	}

	// 根据验证类型检查用户是否存在
	var user models.User
	err := r.Resolver.DB.Where("email = ?", email).First(&user).Error

	if typeArg == VerificationTypeRegister {
		// 注册验证：邮箱不应该存在
		if err == nil {
			return &GeneralResponse{
				Success: false,
				Message: strPtr("该邮箱已被注册"),
				Code:    strPtr("EMAIL_EXISTS"),
			}, nil
		}
	} else {
		// 登录或重置密码：邮箱必须存在
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return &GeneralResponse{
				Success: false,
				Message: strPtr("用户不存在"),
				Code:    strPtr("USER_NOT_FOUND"),
			}, nil
		}
		if err != nil {
			return nil, fmt.Errorf("数据库查询失败: %w", err)
		}
	}

	// 调用统一认证服务发送验证码（内部处理生成与存储）
	authService := services.NewAuthService(r.Resolver.DB)
	if err := authService.SendVerificationCode(email, string(typeArg)); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(err.Error()),
			Code:    strPtr("EMAIL_SEND_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("验证码已发送到您的邮箱"),
		Code:    strPtr("VERIFICATION_CODE_SENT"),
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input VerifyEmailInput) (*GeneralResponse, error) {
	// 验证输入参数
	if input.Email == "" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("邮箱地址不能为空"),
			Code:    strPtr("EMAIL_REQUIRED"),
		}, nil
	}

	if len(input.Code) < 4 {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("验证码格式错误"),
			Code:    strPtr("INVALID_CODE"),
		}, nil
	}

	// 验证验证码（按类型）
	if !verifyCode(input.Email, input.Code, string(input.Type)) {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("验证码错误或已过期"),
			Code:    strPtr("INVALID_OR_EXPIRED_CODE"),
		}, nil
	}

	// 查找用户
	var user models.User
	if err := r.Resolver.DB.Where("email = ?", input.Email).First(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			// 验证成功但用户不存在，删除验证码
			deleteVerificationCode(input.Email, string(input.Type))
			return &GeneralResponse{
				Success: false,
				Message: strPtr("用户不存在"),
				Code:    strPtr("USER_NOT_FOUND"),
			}, nil
		}
		return nil, fmt.Errorf("数据库查询失败: %w", err)
	}

	// 根据验证类型执行相应操作
	switch input.Type {
	case VerificationTypeRegister, VerificationTypeLogin:
		// 注册或登录验证：标记邮箱为已验证
		if !user.IsVerified {
			now := time.Now()
			user.IsVerified = true
			user.EmailVerifiedAt = &now
			if err := r.Resolver.DB.Save(&user).Error; err != nil {
				return nil, fmt.Errorf("更新用户验证状态失败: %w", err)
			}
		}
	case VerificationTypeResetPassword:
		// 密码重置验证：验证成功即可，不需要更新用户状态
		// 实际的密码重置在 confirmPasswordReset 中处理
	}

	// 验证成功，删除验证码
	deleteVerificationCode(input.Email, string(input.Type))

	return &GeneralResponse{
		Success: true,
		Message: strPtr("邮箱验证成功"),
		Code:    strPtr("EMAIL_VERIFIED"),
	}, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input RequestPasswordResetInput) (*GeneralResponse, error) {
	authService := services.NewAuthService(r.Resolver.DB)
	if err := authService.RequestPasswordReset(input.Email); err != nil {
		// 即使失败也返回一种模糊的信息（或者根据错误类型返回特定错误，但在 AuthService 中 RequestPasswordReset 即使找不到用户也返回 nil 或特定错误）
		// AuthService 目前对于找不到用户返回 ErrUserNotFound，但为了安全通常不应暴露。
		// 不过 AuthService.RequestPasswordReset 实现中，如果找不到用户返回 ErrUserNotFound。
		// 我们在这里需要决定是否暴露。原代码是不暴露的。
		// 查看 AuthService 实现:
		// if errors.Is(err, gorm.ErrRecordNotFound) { return models.ErrUserNotFound }
		// 所以如果返回 ErrUserNotFound，我们应该吞掉错误并返回成功消息。

		// 稍微改一下策略：AuthService的RequestPasswordReset如果返回ErrUserNotFound，我们应该视为"成功"（即不让前端知道失败）。
		// 但 AuthService 现在的实现是直接返回 error。

		// 让我们简单点，先调用。
		// 如果是 ErrUserNotFound，我们吞掉。
		// 如果是其他错误，记录日志但返回通用错误。

		// 重新看 AuthService 实现:
		// if errors.Is(err, gorm.ErrRecordNotFound) { return models.ErrUserNotFound }

		if err.Error() == models.ErrUserNotFound.Error() {
			// 用户不存在，为了安全，假装发送成功
		} else {
			return nil, fmt.Errorf("请求密码重置失败: %w", err)
		}
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("如果该邮箱存在，您将收到密码重置邮件"), // 保持一致的安全提示
		Code:    strPtr("RESET_EMAIL_SENT"),
	}, nil
}

// ConfirmPasswordReset is the resolver for the confirmPasswordReset field.
func (r *mutationResolver) ConfirmPasswordReset(ctx context.Context, input ConfirmPasswordResetInput) (*GeneralResponse, error) {
	authService := services.NewAuthService(r.Resolver.DB)
	if err := authService.ConfirmPasswordReset(input.Token, input.NewPassword); err != nil {
		// 处理特定错误
		errMsg := err.Error()
		if errMsg == models.ErrInvalidToken.Error() {
			return &GeneralResponse{
				Success: false,
				Message: strPtr("无效或过期的重置令牌"),
				Code:    strPtr("INVALID_TOKEN"),
			}, nil
		}
		return nil, fmt.Errorf("重置密码失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码重置成功，请使用新密码登录"),
		Code:    strPtr("PASSWORD_RESET_SUCCESS"),
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input UpdateProfileInput) (*User, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 更新用户信息
	updates := map[string]interface{}{}

	if input.Username != nil {
		// 检查用户名是否已存在
		var existingUser models.User
		if err := r.Resolver.DB.Where("username = ? AND id != ?", *input.Username, user.ID).First(&existingUser).Error; err == nil {
			return nil, fmt.Errorf("用户名已存在")
		}
		updates["username"] = *input.Username
	}

	if input.Bio != nil {
		updates["bio"] = *input.Bio
	}

	if input.Avatar != nil {
		updates["avatar"] = *input.Avatar
	}

	// 如果没有更新内容，直接返回当前用户信息
	if len(updates) == 0 {
		return convertToGraphQLUser(user), nil
	}

	// 执行更新
	if err := r.Resolver.DB.Model(user).Updates(updates).Error; err != nil {
		return nil, fmt.Errorf("更新用户信息失败: %w", err)
	}

	// 重新加载用户信息
	if err := r.Resolver.DB.First(user, user.ID).Error; err != nil {
		return nil, fmt.Errorf("获取更新后的用户信息失败: %w", err)
	}

	return convertToGraphQLUser(user), nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, currentPassword string, newPassword string) (*GeneralResponse, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 验证输入参数
	if currentPassword == "" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("当前密码不能为空"),
			Code:    strPtr("CURRENT_PASSWORD_REQUIRED"),
		}, nil
	}

	if newPassword == "" || len(newPassword) < 6 {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("新密码长度不能少于6位"),
			Code:    strPtr("PASSWORD_TOO_SHORT"),
		}, nil
	}

	// 验证当前密码是否正确
	if !user.CheckPassword(currentPassword) {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("当前密码错误"),
			Code:    strPtr("INVALID_CURRENT_PASSWORD"),
		}, nil
	}

	// 检查新密码和当前密码是否相同
	if currentPassword == newPassword {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("新密码不能与当前密码相同"),
			Code:    strPtr("PASSWORD_UNCHANGED"),
		}, nil
	}

	// 设置新密码
	if err := user.SetPassword(newPassword); err != nil {
		return nil, fmt.Errorf("密码加密失败: %w", err)
	}

	// 保存到数据库
	if err := r.Resolver.DB.Save(user).Error; err != nil {
		return nil, fmt.Errorf("更新密码失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("密码修改成功"),
		Code:    strPtr("PASSWORD_CHANGED"),
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input CreatePostInput) (*BlogPost, error) {
	// 获取当前用户（需已验证）
	user, err := requireVerified(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换输入参数
	createInput := &models.CreateBlogPostInput{
		Title:       input.Title,
		Content:     input.Content,
		AccessLevel: "PUBLIC", // 默认值
	}

	// 处理可选字段
	if input.Slug != nil {
		createInput.Slug = *input.Slug
	}

	if input.Excerpt != nil {
		createInput.Excerpt = *input.Excerpt
	}

	if input.CoverImageURL != nil {
		createInput.CoverImageURL = *input.CoverImageURL
	}

	if input.AccessLevel != nil {
		var accessLevel string
		switch *input.AccessLevel {
		case AccessLevelPublic:
			accessLevel = "PUBLIC"
		case AccessLevelPrivate:
			accessLevel = "PRIVATE"
		case AccessLevelRestricted:
			accessLevel = "RESTRICTED"
		}
		createInput.AccessLevel = accessLevel
	}

	if input.Status != nil {
		var status string
		switch *input.Status {
		case PostStatusDraft:
			status = "DRAFT"
		case PostStatusPublished:
			status = "PUBLISHED"
		case PostStatusArchived:
			status = "ARCHIVED"
		}
		createInput.Status = status
	}

	if input.PublishAt != nil {
		createInput.PublishAt = input.PublishAt
	}

	// 处理标签和分类
	if len(input.Tags) > 0 {
		createInput.Tags = input.Tags
	}

	if len(input.Categories) > 0 {
		createInput.Categories = input.Categories
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	post, err := blogService.CreatePostFromInput(createInput, user.ID)
	if err != nil {
		// 添加详细错误日志
		middleware.GetLogger().Errorw("CreatePost 失败",
			"error", err,
			"userID", user.ID,
			"title", input.Title,
			"contentLength", len(input.Content))
		return nil, fmt.Errorf("创建文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(post, user), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input UpdatePostInput) (*BlogPost, error) {
	// 使用统一ID解析逻辑
	helper := services.NewResolverHelper(r.Resolver.DB)

	// 获取当前用户（需邮箱验证）
	user, err := requireVerifiedSafe(ctx, r.Resolver.DB)
	if err != nil {
		return nil, err
	}

	// 解析并获取文章（支持数字ID和Slug）
	post, err := helper.ResolveBlogPost(id, &user.ID, user.Role, true)
	if err != nil {
		return nil, HandleBusinessError(err)
	}

	// 转换输入参数
	updateInput := &models.UpdateBlogPostInput{}

	// 处理可选字段
	if input.Title != nil {
		updateInput.Title = input.Title
	}

	if input.Content != nil {
		updateInput.Content = input.Content
	}

	if input.Slug != nil {
		updateInput.Slug = input.Slug
	}

	if input.Excerpt != nil {
		updateInput.Excerpt = input.Excerpt
	}

	if input.CoverImageURL != nil {
		updateInput.CoverImageURL = input.CoverImageURL
	}

	if input.AccessLevel != nil {
		var accessLevel string
		switch *input.AccessLevel {
		case AccessLevelPublic:
			accessLevel = "PUBLIC"
		case AccessLevelPrivate:
			accessLevel = "PRIVATE"
		case AccessLevelRestricted:
			accessLevel = "RESTRICTED"
		}
		updateInput.AccessLevel = &accessLevel
	}

	if input.Status != nil {
		var status string
		switch *input.Status {
		case PostStatusDraft:
			status = "DRAFT"
		case PostStatusPublished:
			status = "PUBLISHED"
		case PostStatusArchived:
			status = "ARCHIVED"
		}
		updateInput.Status = &status
	}

	if input.ChangeLog != nil {
		updateInput.ChangeLog = *input.ChangeLog
	}

	// 处理标签和分类
	if len(input.Tags) > 0 {
		updateInput.Tags = input.Tags
	}

	if len(input.Categories) > 0 {
		updateInput.Categories = input.Categories
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	updatedPost, err := blogService.UpdatePostFromInput(post.ID, updateInput, user.ID, user.Role)
	if err != nil {
		return nil, HandleBusinessError(err)
	}

	return convertToGraphQLBlogPostWithUser(updatedPost, user), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (*GeneralResponse, error) {
	// 使用统一ID解析逻辑
	helper := services.NewResolverHelper(r.Resolver.DB)

	// 获取当前用户
	user, err := getUserFromContextSafe(ctx, r.Resolver.DB)
	if err != nil {
		return nil, err
	}

	// 解析并获取文章（支持数字ID和Slug）
	post, err := helper.ResolveBlogPost(id, &user.ID, user.Role, true)
	if err != nil {
		return nil, HandleBusinessError(err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	err = blogService.DeletePost(post.ID, user.ID, user.Role)
	if err != nil {
		return nil, HandleBusinessError(err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("文章删除成功"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// PublishPost is the resolver for the publishPost field.
func (r *mutationResolver) PublishPost(ctx context.Context, id string) (*BlogPost, error) {
	// 使用统一ID解析逻辑
	helper := services.NewResolverHelper(r.Resolver.DB)

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 解析并获取文章（支持数字ID和Slug）
	post, err := helper.ResolveBlogPost(id, &user.ID, user.Role, true)
	if err != nil {
		return nil, fmt.Errorf("获取文章失败: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	publishedPost, err := blogService.PublishPost(post.ID, user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("发布文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(publishedPost, user), nil
}

// ArchivePost is the resolver for the archivePost field.
func (r *mutationResolver) ArchivePost(ctx context.Context, id string) (*BlogPost, error) {
	// 使用统一ID解析逻辑
	helper := services.NewResolverHelper(r.Resolver.DB)

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 解析并获取文章（支持数字ID和Slug）
	post, err := helper.ResolveBlogPost(id, &user.ID, user.Role, true)
	if err != nil {
		return nil, fmt.Errorf("获取文章失败: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	archivedPost, err := blogService.ArchivePost(post.ID, user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("归档文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(archivedPost, user), nil
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, id string) (*BlogPost, error) {
	// 使用统一ID解析逻辑
	helper := services.NewResolverHelper(r.Resolver.DB)

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 解析并获取文章（支持数字ID和Slug）
	post, err := helper.ResolveBlogPost(id, &user.ID, user.Role, true)
	if err != nil {
		return nil, fmt.Errorf("获取文章失败: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	likedPost, err := blogService.LikePost(post.ID, user.ID)
	if err != nil {
		return nil, fmt.Errorf("点赞文章失败: %w", err)
	}

	// 设置点赞状态
	graphqlPost := convertToGraphQLBlogPostWithUser(likedPost, user)
	graphqlPost.IsLiked = true

	return graphqlPost, nil
}

// UnlikePost is the resolver for the unlikePost field.
func (r *mutationResolver) UnlikePost(ctx context.Context, id string) (*BlogPost, error) {
	// 使用统一ID解析逻辑
	helper := services.NewResolverHelper(r.Resolver.DB)

	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 解析并获取文章（支持数字ID和Slug）
	post, err := helper.ResolveBlogPost(id, &user.ID, user.Role, true)
	if err != nil {
		return nil, fmt.Errorf("获取文章失败: %w", err)
	}

	// 调用博客服务
	blogService := services.NewBlogService(r.Resolver.DB)
	unlikedPost, err := blogService.UnlikePost(post.ID, user.ID)
	if err != nil {
		return nil, fmt.Errorf("取消点赞失败: %w", err)
	}

	// 设置点赞状态
	graphqlPost := convertToGraphQLBlogPostWithUser(unlikedPost, user)
	graphqlPost.IsLiked = false

	return graphqlPost, nil
}

// UploadImage is the resolver for the uploadImage field.
func (r *mutationResolver) UploadImage(ctx context.Context, file graphql.Upload) (*ImageUploadResponse, error) {
	// 获取当前用户（需已验证邮箱）
	user, err := requireVerified(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 验证文件是否存在
	if file.File == nil {
		return nil, fmt.Errorf("文件不能为空")
	}

	// 使用文件服务上传图片
	fileService := services.NewFileService()
	result, err := fileService.UploadImage(file, user.ID)
	if err != nil {
		return nil, fmt.Errorf("上传图片失败: %w", err)
	}

	// 转换服务响应到GraphQL响应
	return &ImageUploadResponse{
		ImageURL:  result.ImageURL,
		DeleteURL: result.DeleteURL,
		Filename:  result.Filename,
		Size:      result.Size,
	}, nil
}

// AdminCreateUser is the resolver for the adminCreateUser field.
func (r *mutationResolver) AdminCreateUser(ctx context.Context, input AdminCreateUserInput) (*User, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 检查用户名是否已存在
	var existingUser models.User
	if err := r.DB.Where("username = ?", input.Username).First(&existingUser).Error; err == nil {
		return nil, ErrUserExists
	}

	// 检查邮箱是否已存在
	if err := r.DB.Where("email = ?", input.Email).First(&existingUser).Error; err == nil {
		return nil, GraphQLError{Message: "邮箱已被使用", Code: "EMAIL_EXISTS"}
	}

	// 创建新用户
	role := "user" // 默认角色
	if input.Role != nil {
		role = string(*input.Role)
	}

	user := models.User{
		Username:   input.Username,
		Email:      input.Email,
		Password:   input.Password, // 应该在模型中自动哈希
		Role:       role,
		IsVerified: *input.IsVerified,
		IsActive:   true,
	}

	if err := r.DB.Create(&user).Error; err != nil {
		return nil, fmt.Errorf("创建用户失败: %w", err)
	}

	return convertToGraphQLUser(&user), nil
}

// AdminUpdateUser is the resolver for the adminUpdateUser field.
func (r *mutationResolver) AdminUpdateUser(ctx context.Context, id string, username *string, email *string, role *UserRole, isVerified *bool, isActive *bool) (*User, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 解析用户ID
	userID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 查找用户
	var user models.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 更新字段
	if username != nil {
		// 检查用户名是否已被其他用户使用
		var existingUser models.User
		if err := r.DB.Where("username = ? AND id != ?", *username, userID).First(&existingUser).Error; err == nil {
			return nil, GraphQLError{Message: "用户名已被使用", Code: "USERNAME_EXISTS"}
		}
		user.Username = *username
	}

	if email != nil {
		// 检查邮箱是否已被其他用户使用
		var existingUser models.User
		if err := r.DB.Where("email = ? AND id != ?", *email, userID).First(&existingUser).Error; err == nil {
			return nil, GraphQLError{Message: "邮箱已被使用", Code: "EMAIL_EXISTS"}
		}
		user.Email = *email
	}

	logger := middleware.GetLogger()

	if role != nil {
		logger.Infow("更新用户角色", "userId", userID, "oldRole", user.Role, "newRole", string(*role))
		user.Role = string(*role)
	}

	if isVerified != nil {
		user.IsVerified = *isVerified
	}

	if isActive != nil {
		user.IsActive = *isActive
	}

	// 保存更新
	if err := r.DB.Save(&user).Error; err != nil {
		logger.Errorw("更新用户失败", "userId", userID, "error", err)
		return nil, fmt.Errorf("更新用户失败: %w", err)
	}

	logger.Infow("用户更新成功", "userId", userID, "username", user.Username, "role", user.Role)

	return convertToGraphQLUser(&user), nil
}

// AdminDeleteUser is the resolver for the adminDeleteUser field.
func (r *mutationResolver) AdminDeleteUser(ctx context.Context, id string) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 解析用户ID
	userID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 查找用户
	var user models.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 不能删除管理员账户（安全限制）
	if user.Role == "ADMIN" {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("不能删除管理员账户"),
			Code:    strPtr("CANNOT_DELETE_ADMIN"),
		}, nil
	}

	// 开始事务，同时删除用户相关数据
	tx := r.DB.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// 删除用户的文章（软删除）
	if err := tx.Where("author_id = ?", userID).Delete(&models.BlogPost{}).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("删除用户文章失败: %w", err)
	}

	// 删除用户的评论
	if err := tx.Where("user_id = ?", userID).Delete(&models.BlogPostComment{}).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("删除用户评论失败: %w", err)
	}

	// 删除用户账户
	if err := tx.Delete(&user).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("删除用户失败: %w", err)
	}

	if err := tx.Commit().Error; err != nil {
		return nil, fmt.Errorf("提交删除用户事务失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("用户删除成功"),
		Code:    strPtr("DELETE_SUCCESS"),
	}, nil
}

// CreateInviteCode is the resolver for the createInviteCode field.
func (r *mutationResolver) CreateInviteCode(ctx context.Context, input CreateInviteCodeInput) (*InviteCode, error) {
	// 验证管理员权限
	currentUser, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 生成唯一的邀请码
	code := models.GenerateInviteCode()

	// 验证邀请码唯一性
	var existingCode models.InviteCode
	if err := r.DB.Where("code = ?", code).First(&existingCode).Error; err == nil {
		// 如果存在重复，重新生成
		code = models.GenerateInviteCode()
	}

	// 设置默认值
	maxUses := 1
	if input.MaxUses != nil {
		maxUses = *input.MaxUses
	}

	// 创建邀请码
	inviteCode := models.InviteCode{
		Code:        code,
		CreatedByID: currentUser.ID,
		MaxUses:     maxUses,
		CurrentUses: 0,
		IsActive:    true,
	}

	// 处理可选字段
	if input.Description != nil {
		inviteCode.Description = *input.Description
	}

	if !input.ExpiresAt.IsZero() {
		inviteCode.ExpiresAt = &input.ExpiresAt
	}

	// 保存到数据库
	if err := r.DB.Create(&inviteCode).Error; err != nil {
		return nil, fmt.Errorf("创建邀请码失败: %w", err)
	}

	// 预加载关联数据
	if err := r.DB.Preload("CreatedBy").First(&inviteCode, inviteCode.ID).Error; err != nil {
		return nil, fmt.Errorf("获取邀请码详情失败: %w", err)
	}

	// 转换为GraphQL类型
	var description *string
	if inviteCode.Description != "" {
		description = &inviteCode.Description
	}

	var expiresAt time.Time
	if inviteCode.ExpiresAt != nil {
		expiresAt = *inviteCode.ExpiresAt
	} else {
		// 如果没有过期时间，返回一个很远的未来时间表示"永不过期"
		expiresAt = time.Date(2999, 12, 31, 23, 59, 59, 0, time.UTC)
	}

	return &InviteCode{
		ID:          strconv.FormatUint(uint64(inviteCode.ID), 10),
		Code:        inviteCode.Code,
		CreatedBy:   convertToGraphQLUser(&inviteCode.CreatedBy),
		UsedBy:      nil, // 新创建的邀请码未被使用
		UsedAt:      nil,
		ExpiresAt:   expiresAt,
		MaxUses:     inviteCode.MaxUses,
		CurrentUses: inviteCode.CurrentUses,
		IsActive:    inviteCode.IsActive,
		Description: description,
		CreatedAt:   inviteCode.CreatedAt,
	}, nil
}

// DeactivateInviteCode is the resolver for the deactivateInviteCode field.
func (r *mutationResolver) DeactivateInviteCode(ctx context.Context, id string) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 解析邀请码ID
	inviteCodeID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 查找邀请码
	var inviteCode models.InviteCode
	if err := r.DB.First(&inviteCode, inviteCodeID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return &GeneralResponse{
				Success: false,
				Message: strPtr("邀请码不存在"),
				Code:    strPtr("INVITE_CODE_NOT_FOUND"),
			}, nil
		}
		return nil, fmt.Errorf("查询邀请码失败: %w", err)
	}

	// 检查邀请码是否已经被停用
	if !inviteCode.IsActive {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("邀请码已经被停用"),
			Code:    strPtr("INVITE_CODE_ALREADY_INACTIVE"),
		}, nil
	}

	// 停用邀请码
	if err := r.DB.Model(&inviteCode).Update("is_active", false).Error; err != nil {
		return nil, fmt.Errorf("停用邀请码失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("邀请码已成功停用"),
		Code:    strPtr("DEACTIVATE_SUCCESS"),
	}, nil
}

// ClearCache is the resolver for the clearCache field.
func (r *mutationResolver) ClearCache(ctx context.Context) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 统计清理的缓存数量
	var clearedCount int

	// 1. 清理全局缓存
	globalCache := models.GetCache()
	if globalCache != nil {
		clearedCount += globalCache.Count()
		globalCache.Clear()
	}

	// 2. 清理搜索缓存
	searchCache := services.GetGlobalSearchCache()
	if searchCache != nil {
		clearedCount += searchCache.GetCacheStats()["total_items"].(int)
		searchCache.InvalidateAll()
	}

	// 3. 清理邮箱验证缓存（过期的验证码）
	emailVerificationSvc := models.GetEmailVerificationService()
	if emailVerificationSvc != nil {
		// 只能清理过期的，无法访问未导出的 cache 字段
		// 这个服务会自动清理过期的验证码
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("缓存清理成功，共清理 %d 项缓存", clearedCount)),
		Code:    strPtr("CACHE_CLEARED"),
	}, nil
}

// RebuildSearchIndex is the resolver for the rebuildSearchIndex field.
func (r *mutationResolver) RebuildSearchIndex(ctx context.Context) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	logger := middleware.GetLogger()
	logger.Infow("开始重建搜索索引")

	// 1. 清空 FTS 表
	if err := r.DB.Exec("DELETE FROM blog_post_fts").Error; err != nil {
		logger.Errorw("清空FTS表失败", "error", err)
		// 如果表不存在，继续执行
	}

	// 2. 获取所有已发布的文章
	var posts []models.BlogPost
	if err := r.DB.Where("status = ?", "PUBLISHED").Find(&posts).Error; err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("获取文章失败: %v", err)),
			Code:    strPtr("REBUILD_INDEX_FAILED"),
		}, nil
	}

	// 3. 重新索引所有文章到FTS表
	successCount := 0
	for _, post := range posts {
		insertSQL := `INSERT INTO blog_post_fts(rowid, title, content, tags, categories)
			VALUES (?, ?, ?, ?, ?)`

		if err := r.DB.Exec(insertSQL, post.ID, post.Title, post.Content, post.Tags, post.Categories).Error; err != nil {
			logger.Errorw("索引文章失败", "post_id", post.ID, "error", err)
			continue
		}
		successCount++
	}

	// 4. 清空搜索缓存
	searchCache := services.GetGlobalSearchCache()
	if searchCache != nil {
		searchCache.InvalidateAll()
	}

	logger.Infow("搜索索引重建完成", "total", len(posts), "success", successCount)

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("搜索索引重建完成，共索引 %d/%d 篇文章", successCount, len(posts))),
		Code:    strPtr("INDEX_REBUILT"),
	}, nil
}

// SyncNotion is the resolver for the syncNotion field.
// SyncNotion is the resolver for the syncNotion field.
// SyncNotion is the resolver for the syncNotion field.
func (r *mutationResolver) SyncNotion(ctx context.Context, pageID *string) (*GeneralResponse, error) {
	// 获取当前用户（需管理员权限）
	user, err := requireAdmin(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	if r.Resolver.NotionService == nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("Notion服务未初始化，请检查是否配置了 NOTION_API_KEY"),
			Code:    strPtr("NOTION_SERVICE_NOT_INIT"),
		}, nil
	}

	targetPageID := ""
	if pageID != nil {
		targetPageID = *pageID
	}

	// 执行同步
	if err := r.Resolver.NotionService.SyncPosts(ctx, user, targetPageID); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("同步失败: %v", err)),
			Code:    strPtr("SYNC_FAILED"),
		}, nil
	}

	successMsg := "Notion文章同步成功"
	if targetPageID != "" {
		successMsg = fmt.Sprintf("Notion页面 %s 同步成功", targetPageID)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(successMsg),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// UpdateGitHubConfig is the resolver for the updateGitHubConfig field.
func (r *mutationResolver) UpdateGitHubConfig(ctx context.Context, repo string, token string) (*GeneralResponse, error) {
	if err := models.SetSetting(r.DB, "github_repo", repo); err != nil {
		return nil, err
	}
	if err := models.SetSensitiveSetting(r.DB, "github_token", token); err != nil {
		return nil, err
	}
	return &GeneralResponse{Success: true, Message: strPtr("GitHub config updated")}, nil
}

// DeployToGitHubPages is the resolver for the deployToGitHubPages field.
func (r *mutationResolver) DeployToGitHubPages(ctx context.Context) (*GeneralResponse, error) {
	repo, err := models.GetSetting(r.DB, "github_repo")
	if err != nil {
		return nil, fmt.Errorf("github repo not configured")
	}
	token, err := models.GetSensitiveSetting(r.DB, "github_token")
	if err != nil || token == "" {
		return nil, fmt.Errorf("github token not configured or decryption failed")
	}

	parts := strings.Split(repo, "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("invalid repo format, expected user/repo")
	}

	owner, name := parts[0], parts[1]

	// 1. Export JSON data
	tmpDir, err := os.MkdirTemp("", "c404-static-*")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tmpDir)

	if err := r.DeployService.ExportDataToJSON(tmpDir); err != nil {
		return nil, err
	}

	// 2. Push to GitHub
	if err := r.DeployService.DeployToGitHubPages(ctx, owner, name, token, tmpDir); err != nil {
		return nil, err
	}

	return &GeneralResponse{Success: true, Message: strPtr("Deployed successfully")}, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input CreateCommentInput) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换博客文章ID
	blogPostID, err := strconv.ParseUint(input.BlogPostID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 转换父评论ID（如果提供）
	var parentID *uint
	if input.ParentID != nil {
		pid, err := strconv.ParseUint(*input.ParentID, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("无效的父评论ID: %w", err)
		}
		parentIDUint := uint(pid)
		parentID = &parentIDUint
	}

	// 准备服务层输入
	serviceInput := &services.CreateCommentInput{
		Content:    input.Content,
		BlogPostID: uint(blogPostID),
		ParentID:   parentID,
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 创建评论
	comment, err := commentService.CreateComment(serviceInput, user.ID)
	if err != nil {
		return nil, fmt.Errorf("创建评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, input UpdateCommentInput) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 更新评论
	comment, err := commentService.UpdateComment(uint(commentID), input.Content, user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("更新评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (*GeneralResponse, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 删除评论
	err = commentService.DeleteComment(uint(commentID), user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("删除评论失败: %w", err)
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("评论删除成功"),
		Code:    strPtr("DELETE_SUCCESS"),
	}, nil
}

// LikeComment is the resolver for the likeComment field.
func (r *mutationResolver) LikeComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 点赞评论
	comment, err := commentService.LikeComment(uint(commentID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("点赞评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// UnlikeComment is the resolver for the unlikeComment field.
func (r *mutationResolver) UnlikeComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 取消点赞评论
	comment, err := commentService.UnlikeComment(uint(commentID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("取消点赞评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// ReportComment is the resolver for the reportComment field.
func (r *mutationResolver) ReportComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 创建评论服务实例
	commentService := services.NewCommentService(r.Resolver.DB)

	// 举报评论
	comment, err := commentService.ReportComment(uint(commentID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("举报评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(comment), nil
}

// ApproveComment is the resolver for the approveComment field.
func (r *mutationResolver) ApproveComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 检查管理员权限
	if user.Role != "ADMIN" {
		return nil, fmt.Errorf("需要管理员权限")
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 获取评论
	var comment models.BlogPostComment
	if err := r.Resolver.DB.Preload("User").Preload("BlogPost").First(&comment, commentID).Error; err != nil {
		return nil, fmt.Errorf("评论不存在: %w", err)
	}

	// 更新审核状态
	comment.IsApproved = true
	if err := r.Resolver.DB.Save(&comment).Error; err != nil {
		return nil, fmt.Errorf("审核评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(&comment), nil
}

// RejectComment is the resolver for the rejectComment field.
func (r *mutationResolver) RejectComment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	// 检查管理员权限
	if user.Role != "ADMIN" {
		return nil, fmt.Errorf("需要管理员权限")
	}

	// 转换评论ID
	commentID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 获取评论
	var comment models.BlogPostComment
	if err := r.Resolver.DB.Preload("User").Preload("BlogPost").First(&comment, commentID).Error; err != nil {
		return nil, fmt.Errorf("评论不存在: %w", err)
	}

	// 更新审核状态
	comment.IsApproved = false
	if err := r.Resolver.DB.Save(&comment).Error; err != nil {
		return nil, fmt.Errorf("拒绝评论失败: %w", err)
	}

	// 转换为GraphQL类型
	return convertToGraphQLComment(&comment), nil
}

// MergeTags is the resolver for the mergeTags field.
func (r *mutationResolver) MergeTags(ctx context.Context, sourceTag string, targetTag string) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 执行合并操作
	if err := tagService.MergeTags(sourceTag, targetTag); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("合并标签失败: %v", err)),
			Code:    strPtr("MERGE_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("成功将标签 '%s' 合并到 '%s'", sourceTag, targetTag)),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// MergeCategories is the resolver for the mergeCategories field.
func (r *mutationResolver) MergeCategories(ctx context.Context, sourceCategory string, targetCategory string) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 执行合并操作
	if err := tagService.MergeCategories(sourceCategory, targetCategory); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("合并分类失败: %v", err)),
			Code:    strPtr("MERGE_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("成功将分类 '%s' 合并到 '%s'", sourceCategory, targetCategory)),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// BatchUpdateTags is the resolver for the batchUpdateTags field.
func (r *mutationResolver) BatchUpdateTags(ctx context.Context, input BatchUpdateTagsInput) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 转换 postIDs 为 uint
	postIDs := make([]uint, len(input.PostIds))
	for i, id := range input.PostIds {
		postID, err := strconv.ParseUint(id, 10, 32)
		if err != nil {
			return &GeneralResponse{
				Success: false,
				Message: strPtr(fmt.Sprintf("无效的文章ID: %s", id)),
				Code:    strPtr("INVALID_POST_ID"),
			}, nil
		}
		postIDs[i] = uint(postID)
	}

	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 执行批量更新
	if err := tagService.BatchUpdateTags(postIDs, input.Tags, string(input.Operation)); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("批量更新标签失败: %v", err)),
			Code:    strPtr("BATCH_UPDATE_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("成功更新 %d 篇文章的标签", len(postIDs))),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// BatchUpdateCategories is the resolver for the batchUpdateCategories field.
func (r *mutationResolver) BatchUpdateCategories(ctx context.Context, input BatchUpdateCategoriesInput) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 转换 postIDs 为 uint
	postIDs := make([]uint, len(input.PostIds))
	for i, id := range input.PostIds {
		postID, err := strconv.ParseUint(id, 10, 32)
		if err != nil {
			return &GeneralResponse{
				Success: false,
				Message: strPtr(fmt.Sprintf("无效的文章ID: %s", id)),
				Code:    strPtr("INVALID_POST_ID"),
			}, nil
		}
		postIDs[i] = uint(postID)
	}

	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 执行批量更新
	if err := tagService.BatchUpdateCategories(postIDs, input.Categories, string(input.Operation)); err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("批量更新分类失败: %v", err)),
			Code:    strPtr("BATCH_UPDATE_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("成功更新 %d 篇文章的分类", len(postIDs))),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// DeleteUnusedTags is the resolver for the deleteUnusedTags field.
func (r *mutationResolver) DeleteUnusedTags(ctx context.Context) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 执行清理操作
	cleaned, err := tagService.DeleteUnusedTags()
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("清理未使用标签失败: %v", err)),
			Code:    strPtr("DELETE_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("成功清理 %d 个未使用的标签", cleaned)),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// DeleteUnusedCategories is the resolver for the deleteUnusedCategories field.
func (r *mutationResolver) DeleteUnusedCategories(ctx context.Context) (*GeneralResponse, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 执行清理操作
	cleaned, err := tagService.DeleteUnusedCategories()
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("清理未使用分类失败: %v", err)),
			Code:    strPtr("DELETE_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr(fmt.Sprintf("成功清理 %d 个未使用的分类", cleaned)),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// MarkNotificationAsRead is the resolver for the markNotificationAsRead field.
func (r *mutationResolver) MarkNotificationAsRead(ctx context.Context, id string) (*Notification, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未登录: %w", err)
	}

	// 解析通知ID
	notificationID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的通知ID: %w", err)
	}

	// 创建通知服务
	notificationService := services.NewNotificationService(r.Resolver.DB)

	// 标记为已读
	notification, err := notificationService.MarkNotificationAsRead(uint(notificationID), user.ID)
	if err != nil {
		return nil, fmt.Errorf("标记通知为已读失败: %w", err)
	}

	return convertToGraphQLNotification(notification), nil
}

// MarkAllNotificationsAsRead is the resolver for the markAllNotificationsAsRead field.
func (r *mutationResolver) MarkAllNotificationsAsRead(ctx context.Context) (*GeneralResponse, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("未登录"),
			Code:    strPtr("UNAUTHORIZED"),
		}, nil
	}

	// 创建通知服务
	notificationService := services.NewNotificationService(r.Resolver.DB)

	// 标记所有通知为已读
	err = notificationService.MarkAllNotificationsAsRead(user.ID)
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("标记所有通知为已读失败: %v", err)),
			Code:    strPtr("MARK_ALL_READ_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("所有通知已标记为已读"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// DeleteNotification is the resolver for the deleteNotification field.
func (r *mutationResolver) DeleteNotification(ctx context.Context, id string) (*GeneralResponse, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("未登录"),
			Code:    strPtr("UNAUTHORIZED"),
		}, nil
	}

	// 解析通知ID
	notificationID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("无效的通知ID"),
			Code:    strPtr("INVALID_ID"),
		}, nil
	}

	// 创建通知服务
	notificationService := services.NewNotificationService(r.Resolver.DB)

	// 删除通知
	err = notificationService.DeleteNotification(uint(notificationID), user.ID)
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("删除通知失败: %v", err)),
			Code:    strPtr("DELETE_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("通知已删除"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// ClearAllNotifications is the resolver for the clearAllNotifications field.
func (r *mutationResolver) ClearAllNotifications(ctx context.Context) (*GeneralResponse, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr("未登录"),
			Code:    strPtr("UNAUTHORIZED"),
		}, nil
	}

	// 创建通知服务
	notificationService := services.NewNotificationService(r.Resolver.DB)

	// 清空所有通知
	err = notificationService.ClearAllNotifications(user.ID)
	if err != nil {
		return &GeneralResponse{
			Success: false,
			Message: strPtr(fmt.Sprintf("清空所有通知失败: %v", err)),
			Code:    strPtr("CLEAR_ALL_FAILED"),
		}, nil
	}

	return &GeneralResponse{
		Success: true,
		Message: strPtr("所有通知已清空"),
		Code:    strPtr("SUCCESS"),
	}, nil
}

// GenerateMechanismTree is the resolver for the generateMechanismTree field.
func (r *queryResolver) GenerateMechanismTree(ctx context.Context, query string) (*models.MechanismNode, error) {
	return r.Resolver.AIService.GenerateMechanismTree(ctx, query)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	// 获取当前用户信息
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未找到用户信息: %w", err)
	}

	// 确保用户对象不为nil
	if user == nil {
		return nil, fmt.Errorf("用户信息为空")
	}

	return convertToGraphQLUser(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	// 仅本人或管理员可查
	current, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}
	// 如果不是管理员，则只能查看自己
	if current.Role != "ADMIN" {
		// 如果请求的ID不是当前用户ID，则拒绝
		reqID, parseErr := strconv.ParseUint(id, 10, 64)
		if parseErr != nil || uint(reqID) != current.ID {
			return nil, fmt.Errorf("权限不足")
		}
	}

	// 解析用户ID
	userID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的用户ID: %w", err)
	}

	// 从数据库获取用户
	var user models.User
	if err := r.Resolver.DB.First(&user, userID).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("用户不存在")
		}
		return nil, fmt.Errorf("数据库错误: %w", err)
	}

	return convertToGraphQLUser(&user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int, search *string, role *UserRole, isVerified *bool) ([]*User, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.User{})

	// 应用搜索条件
	if search != nil && *search != "" {
		dbQuery = dbQuery.Where("username LIKE ? OR email LIKE ?", "%"+*search+"%", "%"+*search+"%")
	}

	// 应用角色过滤
	if role != nil {
		var roleStr string
		switch *role {
		case UserRoleAdmin:
			roleStr = "ADMIN"
		case UserRoleUser:
			roleStr = "USER"
		}
		dbQuery = dbQuery.Where("role = ?", roleStr)
	}

	// 应用验证状态过滤
	if isVerified != nil {
		dbQuery = dbQuery.Where("is_verified = ?", *isVerified)
	}

	// 获取结果
	var users []models.User
	err = dbQuery.Offset(*offset).Limit(*limit).Find(&users).Error
	if err != nil {
		return nil, fmt.Errorf("获取用户列表失败: %w", err)
	}

	// 转换结果
	result := make([]*User, len(users))
	for i, user := range users {
		result[i] = convertToGraphQLUser(&user)
	}

	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id *string, slug *string) (*BlogPost, error) {
	// 使用统一ID解析逻辑
	helper := services.NewResolverHelper(r.Resolver.DB)

	// 获取当前用户信息（如果有的话）
	var currentUserID *uint
	var currentUserRole string
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
		currentUserID = &user.ID
		currentUserRole = user.Role
	}

	// 确定标识符
	var identifier string
	if id != nil {
		identifier = *id
	} else if slug != nil {
		identifier = *slug
	} else {
		return nil, fmt.Errorf("必须提供id或slug")
	}

	// 解析文章（不跳过计数，因为这是查看操作）
	post, err := helper.ResolveBlogPost(identifier, currentUserID, currentUserRole, false)
	if err != nil {
		return nil, fmt.Errorf("获取文章失败: %w", err)
	}

	return convertToGraphQLBlogPostWithUser(post, currentUser), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int, offset *int, filter *PostFilterInput, sort *PostSortInput) ([]*BlogPost, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPost{}).Preload("Author")

	// 权限过滤
	if currentUser == nil || currentUser.Role != "ADMIN" {
		dbQuery = dbQuery.Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'")
	} else if currentUser.Role != "ADMIN" {
		dbQuery = dbQuery.Where("(status = 'PUBLISHED' AND access_level = 'PUBLIC') OR author_id = ?", currentUser.ID)
	}

	// 应用过滤条件
	if filter != nil {
		// 作者过滤
		if filter.AuthorID != nil {
			authorID, err := strconv.ParseUint(*filter.AuthorID, 10, 64)
			if err == nil {
				dbQuery = dbQuery.Where("author_id = ?", authorID)
			}
		}

		// 状态过滤
		if filter.Status != nil {
			var statusStr string
			switch *filter.Status {
			case PostStatusDraft:
				statusStr = "DRAFT"
			case PostStatusPublished:
				statusStr = "PUBLISHED"
			case PostStatusArchived:
				statusStr = "ARCHIVED"
			}
			dbQuery = dbQuery.Where("status = ?", statusStr)
		}

		// 访问级别过滤
		if filter.AccessLevel != nil {
			var accessLevelStr string
			switch *filter.AccessLevel {
			case AccessLevelPublic:
				accessLevelStr = "PUBLIC"
			case AccessLevelPrivate:
				accessLevelStr = "PRIVATE"
			case AccessLevelRestricted:
				accessLevelStr = "RESTRICTED"
			}
			dbQuery = dbQuery.Where("access_level = ?", accessLevelStr)
		}

		// 标签过滤
		if len(filter.Tags) > 0 {
			for _, tag := range filter.Tags {
				dbQuery = dbQuery.Where("tags LIKE ?", "%"+tag+"%")
			}
		}

		// 分类过滤
		if len(filter.Categories) > 0 {
			for _, category := range filter.Categories {
				dbQuery = dbQuery.Where("categories LIKE ?", "%"+category+"%")
			}
		}

		// 搜索过滤
		if filter.Search != nil && *filter.Search != "" {
			searchTerm := "%" + *filter.Search + "%"
			dbQuery = dbQuery.Where("(title LIKE ? OR content LIKE ? OR tags LIKE ? OR categories LIKE ?)", searchTerm, searchTerm, searchTerm, searchTerm)
		}

		// 日期范围过滤
		if filter.DateFrom != nil {
			dbQuery = dbQuery.Where("created_at >= ?", *filter.DateFrom)
		}
		if filter.DateTo != nil {
			dbQuery = dbQuery.Where("created_at <= ?", *filter.DateTo)
		}
	}

	// 应用排序
	orderClause := "created_at DESC"
	if sort != nil && sort.Field != nil && sort.Order != nil {
		// 验证字段名以防止SQL注入
		validFields := map[string]bool{
			"created_at":   true,
			"updated_at":   true,
			"published_at": true,
			"view_count":   true,
			"like_count":   true,
		}

		if validFields[*sort.Field] {
			orderClause = *sort.Field + " " + *sort.Order
		}
	}
	dbQuery = dbQuery.Order(orderClause)

	// 获取结果
	var posts []models.BlogPost
	err := dbQuery.Offset(*offset).Limit(*limit).Find(&posts).Error
	if err != nil {
		return nil, fmt.Errorf("获取文章列表失败: %w", err)
	}

	// 转换结果
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPostWithUser(&post, currentUser)
	}

	return result, nil
}

// PostVersions is the resolver for the postVersions field.
func (r *queryResolver) PostVersions(ctx context.Context, postID string) ([]*BlogPostVersion, error) {
	// 解析文章ID
	id, err := strconv.ParseUint(postID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的文章ID: %w", err)
	}

	// 获取当前用户信息
	currentUser, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("需要登录才能查看文章版本: %w", err)
	}

	// 检查用户是否有权限查看文章版本
	var post models.BlogPost
	if err := r.Resolver.DB.First(&post, id).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("文章不存在")
		}
		return nil, fmt.Errorf("数据库错误: %w", err)
	}

	// 只有文章作者或管理员可以查看版本
	if post.AuthorID != currentUser.ID && currentUser.Role != "ADMIN" {
		return nil, fmt.Errorf("权限不足")
	}

	// 获取版本历史
	var versions []models.BlogPostVersion
	err = r.Resolver.DB.Where("blog_post_id = ?", id).
		Preload("CreatedBy").
		Order("version_num DESC").
		Find(&versions).Error

	if err != nil {
		return nil, fmt.Errorf("获取文章版本失败: %w", err)
	}

	// 转换结果
	result := make([]*BlogPostVersion, len(versions))
	for i, version := range versions {
		result[i] = &BlogPostVersion{
			ID:         strconv.FormatUint(uint64(version.ID), 10),
			VersionNum: version.VersionNum,
			Title:      version.Title,
			Content:    version.Content,
			ChangeLog:  &version.ChangeLog,
			CreatedAt:  version.CreatedAt,
			CreatedBy:  convertToGraphQLUser(&version.CreatedBy),
		}
	}

	return result, nil
}

// SearchPosts is the resolver for the searchPosts field.
func (r *queryResolver) SearchPosts(ctx context.Context, query string, limit *int, offset *int) (*SearchResult, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 获取当前用户信息（如果有的话）
	var userID *uint
	var userRole string = "USER"

	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	result, err := searchService.AdvancedSearchPosts(query, *limit, *offset, userID, userRole)
	if err != nil {
		return nil, fmt.Errorf("搜索失败: %w", err)
	}

	// 转换结果
	posts := make([]*BlogPost, len(result.Posts))
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	for i, post := range result.Posts {
		posts[i] = convertToGraphQLBlogPostWithUser(post, currentUser)
	}

	return &SearchResult{
		Posts: posts,
		Total: int(result.Total),
		Took:  result.Took.String(),
	}, nil
}

// EnhancedSearch is the resolver for the enhancedSearch field.
func (r *queryResolver) EnhancedSearch(ctx context.Context, input SearchInput) (*EnhancedSearchResult, error) {
	// 设置默认值
	query := input.Query
	limit := 10
	offset := 0

	if input.Limit != nil {
		limit = *input.Limit
	}

	if input.Offset != nil {
		offset = *input.Offset
	}

	// 获取当前用户信息（如果有的话）
	var userID *uint
	var userRole string = "USER"

	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		userID = &user.ID
		userRole = user.Role
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	result, err := searchService.AdvancedSearchPosts(query, limit, offset, userID, userRole)
	if err != nil {
		return nil, fmt.Errorf("增强搜索失败: %w", err)
	}

	// 转换结果
	posts := make([]*BlogPost, len(result.Posts))
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	for i, post := range result.Posts {
		posts[i] = convertToGraphQLBlogPostWithUser(post, currentUser)
	}

	// 获取搜索建议
	suggestions, err := searchService.GetSearchSuggestions(query, 5)
	if err != nil {
		// 不中断搜索，只记录错误
		suggestions = []string{}
	}

	// 获取聚合信息
	tagFacets, _ := searchService.GetTagFacets(query, 10)
	categoryFacets, _ := searchService.GetCategoryFacets(query, 10)
	authorFacets, _ := searchService.GetAuthorFacets(query, 10)

	// 转换聚合信息
	tags := make([]*SearchFacetItem, len(tagFacets))
	for i, facet := range tagFacets {
		tags[i] = &SearchFacetItem{
			Value: facet.Value,
			Count: facet.Count,
		}
	}

	categories := make([]*SearchFacetItem, len(categoryFacets))
	for i, facet := range categoryFacets {
		categories[i] = &SearchFacetItem{
			Value: facet.Value,
			Count: facet.Count,
		}
	}

	authors := make([]*SearchFacetItem, len(authorFacets))
	for i, facet := range authorFacets {
		authors[i] = &SearchFacetItem{
			Value: facet.Value,
			Count: facet.Count,
		}
	}

	return &EnhancedSearchResult{
		Posts:       posts,
		Total:       int(result.Total),
		Took:        result.Took.String(),
		Suggestions: suggestions,
		Facets: &SearchFacets{
			Tags:       tags,
			Categories: categories,
			Authors:    authors,
		},
	}, nil
}

// GetSearchSuggestions is the resolver for the getSearchSuggestions field.
func (r *queryResolver) GetSearchSuggestions(ctx context.Context, query string, limit *int) ([]string, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	suggestions, err := searchService.GetSearchSuggestions(query, *limit)
	if err != nil {
		return nil, fmt.Errorf("获取搜索建议失败: %w", err)
	}

	return suggestions, nil
}

// GetTrendingSearches is the resolver for the getTrendingSearches field.
func (r *queryResolver) GetTrendingSearches(ctx context.Context, limit *int) ([]string, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 调用搜索服务
	searchService := r.Resolver.SearchService
	trending, err := searchService.GetTrendingSearches(*limit)
	if err != nil {
		return nil, fmt.Errorf("获取热门搜索词失败: %w", err)
	}

	return trending, nil
}

// GetSearchStats is the resolver for the getSearchStats field.
func (r *queryResolver) GetSearchStats(ctx context.Context) (*SearchStats, error) {
	searchService := r.Resolver.SearchService

	// 统计最近30天的数据
	days := 30

	// 1. 获取总搜索次数
	totalSearches, err := searchService.GetTotalSearchCount(days)
	if err != nil {
		totalSearches = 0
	}

	// 2. 获取热门查询
	stats, err := searchService.GetSearchQueryStats(10, days)
	if err != nil {
		stats = []models.SearchQueryStats{}
	}

	// 转换为 GraphQL 类型
	popularQueries := make([]*PopularQuery, len(stats))
	for i, stat := range stats {
		popularQueries[i] = &PopularQuery{
			Query:        stat.Query,
			Count:        int(stat.Count),
			LastSearched: stat.LastSearched,
		}
	}

	// 3. 获取搜索趋势
	trendData, err := searchService.GetSearchTrends(days)
	if err != nil {
		trendData = []map[string]interface{}{}
	}

	searchTrends := make([]*SearchTrend, len(trendData))
	for i, trend := range trendData {
		date, _ := trend["date"].(string)
		count, _ := trend["count"].(int64)

		searchTrends[i] = &SearchTrend{
			Date:        date,
			SearchCount: int(count),
			TopQueries:  []string{}, // 暂时为空，可以后续添加每日热门查询
		}
	}

	return &SearchStats{
		TotalSearches:  int(totalSearches),
		PopularQueries: popularQueries,
		SearchTrends:   searchTrends,
	}, nil
}

// InviteCodes is the resolver for the inviteCodes field.
func (r *queryResolver) InviteCodes(ctx context.Context, limit *int, offset *int, isActive *bool) ([]*InviteCode, error) {
	// 验证管理员权限
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, HandleAuthError(err)
	}

	if user.Role != "ADMIN" {
		return nil, HandleForbidden()
	}

	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.InviteCode{}).
		Preload("CreatedBy").
		Preload("UsedBy")

	// 应用激活状态过滤
	if isActive != nil {
		dbQuery = dbQuery.Where("is_active = ?", *isActive)
	}

	// 获取结果
	var inviteCodes []models.InviteCode
	err = dbQuery.Offset(*offset).Limit(*limit).Find(&inviteCodes).Error
	if err != nil {
		return nil, fmt.Errorf("获取邀请码列表失败: %w", err)
	}

	// 转换结果
	result := make([]*InviteCode, len(inviteCodes))
	for i, inviteCode := range inviteCodes {
		// 处理可选字段
		var description *string
		if inviteCode.Description != "" {
			description = &inviteCode.Description
		}

		var expiresAt time.Time
		if inviteCode.ExpiresAt != nil {
			expiresAt = *inviteCode.ExpiresAt
		} else {
			// 如果没有过期时间，返回一个很远的未来时间表示"永不过期"
			expiresAt = time.Date(2999, 12, 31, 23, 59, 59, 0, time.UTC)
		}

		result[i] = &InviteCode{
			ID:          strconv.FormatUint(uint64(inviteCode.ID), 10),
			Code:        inviteCode.Code,
			CreatedBy:   convertToGraphQLUser(&inviteCode.CreatedBy),
			UsedBy:      convertToGraphQLUser(inviteCode.UsedBy),
			UsedAt:      inviteCode.UsedAt,
			ExpiresAt:   expiresAt,
			MaxUses:     inviteCode.MaxUses,
			CurrentUses: inviteCode.CurrentUses,
			IsActive:    inviteCode.IsActive,
			Description: description,
			CreatedAt:   inviteCode.CreatedAt,
		}
	}

	return result, nil
}

// ServerDashboard is the resolver for the serverDashboard field.
func (r *queryResolver) ServerDashboard(ctx context.Context) (*ServerDashboard, error) {
	// 获取内存统计信息
	var memStats runtime.MemStats
	runtime.ReadMemStats(&memStats)

	// 格式化内存信息为字符串
	memory := &ServerMemoryStats{
		Alloc:      fmt.Sprintf("%.2f MB", float64(memStats.Alloc)/1024/1024),
		TotalAlloc: fmt.Sprintf("%.2f MB", float64(memStats.TotalAlloc)/1024/1024),
		Sys:        fmt.Sprintf("%.2f MB", float64(memStats.Sys)/1024/1024),
		HeapAlloc:  fmt.Sprintf("%.2f MB", float64(memStats.HeapAlloc)/1024/1024),
		HeapSys:    fmt.Sprintf("%.2f MB", float64(memStats.HeapSys)/1024/1024),
	}

	// 获取主机名
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "unknown"
	}

	// 获取用户数量
	var userCount int64
	if err := r.Resolver.DB.Model(&models.User{}).Count(&userCount).Error; err != nil {
		return nil, fmt.Errorf("获取用户数量失败: %w", err)
	}

	// 获取文章数量
	var postCount int64
	if err := r.Resolver.DB.Model(&models.BlogPost{}).Count(&postCount).Error; err != nil {
		return nil, fmt.Errorf("获取文章数量失败: %w", err)
	}

	// 获取今日注册用户数
	var todayRegistrations int64
	today := time.Now().Truncate(24 * time.Hour)
	if err := r.Resolver.DB.Model(&models.User{}).
		Where("created_at >= ?", today).
		Count(&todayRegistrations).Error; err != nil {
		return nil, fmt.Errorf("获取今日注册用户数失败: %w", err)
	}

	// 获取今日发布文章数
	var todayPosts int64
	if err := r.Resolver.DB.Model(&models.BlogPost{}).
		Where("created_at >= ?", today).
		Count(&todayPosts).Error; err != nil {
		return nil, fmt.Errorf("获取今日发布文章数失败: %w", err)
	}

	// 构建返回结果
	return &ServerDashboard{
		ServerTime:         time.Now(),
		Hostname:           hostname,
		GoVersion:          runtime.Version(),
		CPUCount:           runtime.NumCPU(),
		Goroutines:         runtime.NumGoroutine(),
		Memory:             memory,
		Uptime:             "0 days", // 简化实现，实际应该记录服务启动时间
		UserCount:          int(userCount),
		PostCount:          int(postCount),
		TodayRegistrations: int(todayRegistrations),
		TodayPosts:         int(todayPosts),
	}, nil
}

// GetPopularPosts is the resolver for the getPopularPosts field.
func (r *queryResolver) GetPopularPosts(ctx context.Context, limit *int) ([]*BlogPost, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 限制最大返回数量
	if *limit > 100 {
		*limit = 100
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 查询热门文章，按点赞数和浏览量排序
	var posts []models.BlogPost
	err := r.Resolver.DB.Model(&models.BlogPost{}).
		Preload("Author").
		Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'").
		Joins("LEFT JOIN blog_post_stats stats ON blog_post.id = stats.blog_post_id"). // 正确关联统计表并使用别名
		Order("stats.like_count DESC, stats.view_count DESC, blog_post.created_at DESC").
		Limit(*limit).
		Find(&posts).Error

	if err != nil {
		return nil, fmt.Errorf("获取热门文章失败: %w", err)
	}

	// 转换结果
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPostWithUser(&post, currentUser)
	}

	return result, nil
}

// GetRecentPosts is the resolver for the getRecentPosts field.
func (r *queryResolver) GetRecentPosts(ctx context.Context, limit *int) ([]*BlogPost, error) {
	// 设置默认值
	defaultLimit := 10
	if limit == nil {
		limit = &defaultLimit
	}

	// 限制最大返回数量
	if *limit > 100 {
		*limit = 100
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 查询最新文章，按创建时间排序
	var posts []models.BlogPost
	err := r.Resolver.DB.Model(&models.BlogPost{}).
		Preload("Author").
		Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'").
		Order("created_at DESC").
		Limit(*limit).
		Find(&posts).Error

	if err != nil {
		return nil, fmt.Errorf("获取最新文章失败: %w", err)
	}

	// 转换结果
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPostWithUser(&post, currentUser)
	}

	return result, nil
}

// GetTrendingTags is the resolver for the getTrendingTags field.
func (r *queryResolver) GetTrendingTags(ctx context.Context, limit *int) ([]string, error) {
	// 设置默认值
	defaultLimit := 20
	if limit == nil {
		limit = &defaultLimit
	}

	// 限制最大返回数量
	if *limit > 100 {
		*limit = 100
	}

	// 使用搜索服务获取热门标签
	searchService := r.Resolver.SearchService
	trendingTags, err := searchService.GetTrendingSearches(*limit)
	if err != nil {
		// 如果搜索服务失败，返回空数组而不是错误
		return []string{}, nil
	}

	return trendingTags, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, blogPostID *string, limit *int, offset *int, filter *CommentFilterInput, sort *CommentSortInput) (*CommentResult, error) {
	// 设置默认值
	defaultLimit := 10
	defaultOffset := 0

	if limit == nil {
		limit = &defaultLimit
	}

	if offset == nil {
		offset = &defaultOffset
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPostComment{}).
		Preload("User").
		Preload("BlogPost").
		Preload("Parent").
		Preload("Replies")

	// 如果提供了 blogPostID，按文章筛选
	if blogPostID != nil {
		postID, err := strconv.ParseUint(*blogPostID, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("无效的文章ID: %w", err)
		}
		dbQuery = dbQuery.Where("blog_post_id = ?", postID)
	}

	// 权限过滤 - 只显示已审核的评论，除非是管理员
	if currentUser == nil || currentUser.Role != "ADMIN" {
		dbQuery = dbQuery.Where("is_approved = ?", true)
	}

	// 应用过滤条件
	if filter != nil {
		// 用户ID过滤
		if filter.UserID != nil {
			userID, err := strconv.ParseUint(*filter.UserID, 10, 64)
			if err == nil {
				dbQuery = dbQuery.Where("user_id = ?", userID)
			}
		}

		// 审核状态过滤
		if filter.IsApproved != nil {
			dbQuery = dbQuery.Where("is_approved = ?", *filter.IsApproved)
		}
	}

	// 应用排序
	orderClause := "created_at DESC"
	if sort != nil && sort.Field != nil && sort.Order != nil {
		// 验证字段名以防止SQL注入
		validFields := map[string]bool{
			"created_at": true,
			"like_count": true,
		}

		if validFields[*sort.Field] {
			orderClause = *sort.Field + " " + *sort.Order
		}
	}
	dbQuery = dbQuery.Order(orderClause)

	// 获取总数
	var total int64
	countQuery := dbQuery
	if err := countQuery.Count(&total).Error; err != nil {
		return nil, fmt.Errorf("获取评论总数失败: %w", err)
	}

	// 获取结果
	var comments []models.BlogPostComment
	err := dbQuery.Offset(*offset).Limit(*limit).Find(&comments).Error
	if err != nil {
		return nil, fmt.Errorf("获取评论列表失败: %w", err)
	}

	// 转换结果
	result := make([]*BlogPostComment, len(comments))
	for i, comment := range comments {
		result[i] = convertToGraphQLComment(&comment)
	}

	return &CommentResult{
		Comments: result,
		Total:    int(total),
	}, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*BlogPostComment, error) {
	// 解析评论ID
	commentID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("无效的评论ID: %w", err)
	}

	// 获取当前用户信息（如果有的话）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPostComment{}).
		Preload("User").
		Preload("Parent").
		Preload("Replies").
		Preload("BlogPost").
		Where("id = ?", commentID)

	// 权限过滤 - 只显示已审核的评论，除非是管理员或作者
	if currentUser == nil || currentUser.Role != "ADMIN" {
		dbQuery = dbQuery.Where("is_approved = ?", true)
	}

	// 获取结果
	var comment models.BlogPostComment
	err = dbQuery.First(&comment).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("评论不存在")
		}
		return nil, fmt.Errorf("数据库错误: %w", err)
	}

	return convertToGraphQLComment(&comment), nil
}

// GetTags is the resolver for the getTags field.
func (r *queryResolver) GetTags(ctx context.Context, limit *int, offset *int, search *string) ([]*TagInfo, error) {
	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 获取标签列表
	tags, err := tagService.GetTags(limit, offset, search)
	if err != nil {
		return nil, fmt.Errorf("获取标签列表失败: %w", err)
	}

	// 转换为GraphQL类型
	result := make([]*TagInfo, len(tags))
	for i, tag := range tags {
		posts := make([]*BlogPost, len(tag.Posts))
		for j, post := range tag.Posts {
			posts[j] = convertToGraphQLBlogPostWithUser(post, nil)
		}

		result[i] = &TagInfo{
			Name:  tag.Name,
			Count: tag.Count,
			Posts: posts,
		}
	}

	return result, nil
}

// GetCategories is the resolver for the getCategories field.
func (r *queryResolver) GetCategories(ctx context.Context, limit *int, offset *int, search *string) ([]*CategoryInfo, error) {
	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 获取分类列表
	categories, err := tagService.GetCategories(limit, offset, search)
	if err != nil {
		return nil, fmt.Errorf("获取分类列表失败: %w", err)
	}

	// 转换为GraphQL类型
	result := make([]*CategoryInfo, len(categories))
	for i, category := range categories {
		posts := make([]*BlogPost, len(category.Posts))
		for j, post := range category.Posts {
			posts[j] = convertToGraphQLBlogPostWithUser(post, nil)
		}

		result[i] = &CategoryInfo{
			Name:  category.Name,
			Count: category.Count,
			Posts: posts,
		}
	}

	return result, nil
}

// GetTagCategoryStats is the resolver for the getTagCategoryStats field.
func (r *queryResolver) GetTagCategoryStats(ctx context.Context) (*TagCategoryStats, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.DB)
	if err != nil {
		return nil, err
	}

	// 创建标签服务
	tagService := services.NewTagService(r.Resolver.DB)

	// 获取统计信息
	stats, err := tagService.GetTagCategoryStats()
	if err != nil {
		return nil, fmt.Errorf("获取标签分类统计失败: %w", err)
	}

	// 转换为GraphQL类型
	tags := make([]*TagInfo, len(stats.Tags))
	for i, tag := range stats.Tags {
		posts := make([]*BlogPost, len(tag.Posts))
		for j, post := range tag.Posts {
			posts[j] = convertToGraphQLBlogPostWithUser(post, nil)
		}

		tags[i] = &TagInfo{
			Name:  tag.Name,
			Count: tag.Count,
			Posts: posts,
		}
	}

	categories := make([]*CategoryInfo, len(stats.Categories))
	for i, category := range stats.Categories {
		posts := make([]*BlogPost, len(category.Posts))
		for j, post := range category.Posts {
			posts[j] = convertToGraphQLBlogPostWithUser(post, nil)
		}

		categories[i] = &CategoryInfo{
			Name:  category.Name,
			Count: category.Count,
			Posts: posts,
		}
	}

	return &TagCategoryStats{
		TotalTags:       stats.TotalTags,
		TotalCategories: stats.TotalCategories,
		Tags:            tags,
		Categories:      categories,
	}, nil
}

// GetNotionPages is the resolver for the getNotionPages field.
func (r *queryResolver) GetNotionPages(ctx context.Context) ([]*NotionPage, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	if r.Resolver.NotionService == nil {
		return nil, fmt.Errorf("Notion服务未初始化，请检查后端是否配置了 NOTION_API_KEY")
	}

	pages, err := r.Resolver.NotionService.ListPages(ctx)
	if err != nil {
		return nil, fmt.Errorf("获取Notion页面失败: %w", err)
	}

	var result []*NotionPage
	for _, p := range pages {
		result = append(result, &NotionPage{
			ID:           p.ID,
			Title:        p.Title,
			LastEditedAt: p.LastEditedAt,
			URL:          p.URL,
		})
	}

	return result, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, limit *int, offset *int) ([]*Notification, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未登录: %w", err)
	}

	// 设置默认值
	defaultLimit := 20
	defaultOffset := 0
	if limit == nil {
		limit = &defaultLimit
	}
	if offset == nil {
		offset = &defaultOffset
	}

	// 创建通知服务
	notificationService := services.NewNotificationService(r.Resolver.DB)

	// 获取通知列表
	notifications, _, err := notificationService.GetNotifications(user.ID, *limit, *offset)
	if err != nil {
		return nil, fmt.Errorf("获取通知列表失败: %w", err)
	}

	// 转换为GraphQL类型
	result := make([]*Notification, len(notifications))
	for i, notification := range notifications {
		result[i] = convertToGraphQLNotification(notification)
	}

	return result, nil
}

// UnreadNotificationCount is the resolver for the unreadNotificationCount field.
func (r *queryResolver) UnreadNotificationCount(ctx context.Context) (int, error) {
	// 获取当前用户
	user, err := getUserFromContext(ctx, r.Resolver.DB)
	if err != nil {
		return 0, fmt.Errorf("未登录: %w", err)
	}

	// 创建通知服务
	notificationService := services.NewNotificationService(r.Resolver.DB)

	// 获取未读数量
	count, err := notificationService.GetUnreadNotificationCount(user.ID)
	if err != nil {
		return 0, fmt.Errorf("获取未读通知数量失败: %w", err)
	}

	return int(count), nil
}

// GetGitHubConfig is the resolver for the getGitHubConfig field.
func (r *queryResolver) GetGitHubConfig(ctx context.Context) (*GitHubConfig, error) {
	// 验证管理员权限
	_, err := requireAdmin(ctx, r.Resolver.DB)
	if err != nil {
		return nil, fmt.Errorf("未授权访问: %w", err)
	}

	repo, _ := models.GetSetting(r.DB, "github_repo")
	token, _ := models.GetSensitiveSetting(r.DB, "github_token")

	// 屏蔽令牌，只显示是否存在
	maskedToken := ""
	if token != "" {
		maskedToken = "********"
	}

	return &GitHubConfig{
		Repo:  repo,
		Token: maskedToken,
	}, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *User, limit *int, offset *int) ([]*BlogPost, error) {
	// 解析用户ID
	userID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %v", err)
	}

	// 设置默认值
	defLimit := 10
	defOffset := 0
	if limit == nil {
		limit = &defLimit
	}
	if offset == nil {
		offset = &defOffset
	}

	// 获取当前用户信息（用于权限检查）
	var currentUser *models.User
	if user, err := getUserFromContext(ctx, r.Resolver.DB); err == nil {
		currentUser = user
	}

	// 构建查询
	dbQuery := r.Resolver.DB.Model(&models.BlogPost{}).
		Where("author_id = ?", uint(userID))

	// 权限过滤
	if currentUser == nil || (currentUser.ID != uint(userID) && currentUser.Role != "ADMIN") {
		dbQuery = dbQuery.Where("status = 'PUBLISHED' AND access_level = 'PUBLIC'")
	}

	// 获取结果
	var posts []models.BlogPost
	err = dbQuery.Order("created_at DESC").
		Offset(*offset).
		Limit(*limit).
		Find(&posts).Error
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user posts: %w", err)
	}

	// 转换结果
	result := make([]*BlogPost, len(posts))
	for i, post := range posts {
		result[i] = convertToGraphQLBlogPostWithUser(&post, currentUser)
	}

	return result, nil
}

// PostsCount is the resolver for the postsCount field.
func (r *userResolver) PostsCount(ctx context.Context, obj *User) (int, error) {
	// 解析用户ID
	userID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("invalid user id: %v", err)
	}

	// 使用 DataLoader
	loader := GetDataLoaderFromContext(ctx)
	if loader == nil {
		// Fallback to direct DB query
		var count int64
		err := r.Resolver.DB.Model(&models.BlogPost{}).
			Where("author_id = ? AND status = 'PUBLISHED' AND access_level = 'PUBLIC'", uint(userID)).
			Count(&count).Error
		if err != nil {
			return 0, err
		}
		return int(count), nil
	}

	return loader.LoadPostsCount(ctx, uint(userID))
}

// BlogPost returns BlogPostResolver implementation.
func (r *Resolver) BlogPost() BlogPostResolver { return &blogPostResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type blogPostResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
